#pragma once
#include <string>
enum EscortClientWealth{ECW_PEASANT,ECW_TRAVELLER,ECW_MERCHANT,ECW_RICH,ECW_NOBLE};enum EscortClientPersonality{ECP_GENEROUS,ECP_NORMAL,ECP_STINGY,ECP_SUSPICIOUS};
enum MercContractType{MCT_ESCORT=0,MCT_CARAVAN=1,MCT_SCIENCE=2,MCT_MAIL=4};enum MercContractSource{MCS_TAVERN,MCS_GUILD_HOUSE};enum MercContractRarity{MCR_COMMON,MCR_RARE,MCR_EPIC,MCR_LEGENDARY};
enum MercCaravanSize{MCZ_SMALL,MCZ_MEDIUM,MCZ_LARGE,MCZ_VERY_LARGE};enum MercCargoClass{MCC_BASIC,MCC_COMMON,MCC_IMPORTANT,MCC_PRECIOUS,MCC_EXCEPTIONAL};enum MercStudyClass{MSC_SMALL,MSC_NORMAL,MSC_IMPORTANT,MSC_GRAND};enum MercStudyDuration{MSD_SHORT,MSD_MEDIUM,MSD_LONG,MSD_VERY_LONG};
enum MercEnvironmentTag{MET_NONE=0,MET_TOXIC_GAS=1<<0,MET_ACID=1<<1,MET_ORBITAL_BEAM=1<<2,MET_DUST_STORM=1<<3,MET_EXTREME_HOSTILES=1<<4,MET_CANNIBAL_CAPTURE=1<<5,MET_FOGMEN_CAPTURE=1<<6,MET_SKIN_BANDIT_CAPTURE=1<<7,MET_BEAK_THING_HEAVY=1<<8};
enum EscortBonus{EB_HEALTHY=1<<0,EB_HALF_NOW=1<<1,EB_FAST=1<<2,EB_NO_KO=1<<3,EB_DANGER=1<<4,EB_SUPPLIES=1<<5};
struct MercRewardBreakdown{int base,distance,mission,environment,beforeDanger,afterDanger,afterRarity,guildHouseBonus,beforeNegotiation,negotiation,finalBeforeMissionBonuses;MercRewardBreakdown():base(0),distance(0),mission(0),environment(0),beforeDanger(0),afterDanger(0),afterRarity(0),guildHouseBonus(0),beforeNegotiation(0),negotiation(0),finalBeforeMissionBonuses(0){}};
struct EscortContractData{int schemaVersion;std::string origin,destination,originId,destinationId,routeRegions;MercContractType type;MercContractSource source;MercContractRarity rarity;MercCaravanSize caravanSize;MercCargoClass cargoClass;MercStudyClass studyClass;MercStudyDuration studyDuration;int environmentTags,dangerLevel,groupSize,cargoValue,selectedBonuses,bonusPay,advance,finalPay,totalPay,counterOffers,negotiationPercent,basePay;float distanceKm,danger,initialRate,negotiatedRate;EscortClientWealth wealth;EscortClientPersonality personality;bool prestigious,urgent,advancePaidOnce,settlementPaid;MercRewardBreakdown reward;EscortContractData():schemaVersion(2),type(MCT_ESCORT),source(MCS_TAVERN),rarity(MCR_COMMON),caravanSize(MCZ_SMALL),cargoClass(MCC_BASIC),studyClass(MSC_SMALL),studyDuration(MSD_SHORT),environmentTags(0),dangerLevel(1),groupSize(1),cargoValue(0),selectedBonuses(0),bonusPay(0),advance(0),finalPay(0),totalPay(0),counterOffers(0),negotiationPercent(0),basePay(0),distanceKm(0),danger(1),initialRate(10),negotiatedRate(10),wealth(ECW_TRAVELLER),personality(ECP_NORMAL),prestigious(false),urgent(false),advancePaidOnce(false),settlementPaid(false){}};
struct EscortJourneyData{float seconds,distanceTravelled;int combats,ambushes,dangerousRegions,detours;bool knockedOut,gravelyInjured,mutilated,arrivedOnTime;EscortJourneyData():seconds(0),distanceTravelled(0),combats(0),ambushes(0),dangerousRegions(0),detours(0),knockedOut(false),gravelyInjured(false),mutilated(false),arrivedOnTime(false){}};
