#pragma once
#include "EscortConfig.h"
#include "EscortContract.h"
#include <algorithm>
#include <cmath>
namespace EscortEconomy {
inline int cap(int v){return std::max(0,std::min(v,EscortConfig::AbsoluteContractCap));}inline float rarityMultiplier(MercContractRarity r){static const float v[]={1,1.25f,1.60f,2};return v[std::max(0,std::min(3,(int)r))];}inline float dangerMultiplier(int l){static const float v[]={1,1,1.25f,1.60f,2.10f,2.80f};return v[std::max(1,std::min(5,l))];}
inline int clientImportance(EscortClientWealth w){static const int v[]={0,0,500,1500,3000};return v[std::max(0,std::min(4,(int)w))];}inline MercCaravanSize caravanSizeFor(int n){return n<=2?MCZ_SMALL:n<=4?MCZ_MEDIUM:n<=6?MCZ_LARGE:MCZ_VERY_LARGE;}inline int caravanSizeBonus(MercCaravanSize s){static const int v[]={0,1000,2500,4000};return v[(int)s];}inline int cargoBonus(MercCargoClass c){static const int v[]={0,500,1500,3000,5000};return v[(int)c];}inline int studyBonus(MercStudyClass s){static const int v[]={750,1500,3000,5000};return v[(int)s];}inline int studyDurationBonus(MercStudyDuration d){static const int v[]={0,750,1500,3000};return v[(int)d];}inline int environmentalBonus(int tags){if(!tags)return 0;int major=tags&(MET_TOXIC_GAS|MET_ACID|MET_ORBITAL_BEAM|MET_SKIN_BANDIT_CAPTURE|MET_EXTREME_HOSTILES|MET_BEAK_THING_HEAVY);int important=tags&(MET_CANNIBAL_CAPTURE|MET_FOGMEN_CAPTURE);return major?2000:important?1000:500;}inline int minimumFor(MercContractType t){return t==MCT_CARAVAN?EscortConfig::CaravanMinimum:t==MCT_SCIENCE?EscortConfig::ScienceMinimum:t==MCT_MAIL?EscortConfig::MailMinimum:EscortConfig::EscortMinimum;}
inline void calculate(EscortContractData& c,int pct){if(!_finite(c.distanceKm)||c.distanceKm<0)c.distanceKm=0;c.dangerLevel=std::max(1,std::min(5,c.dangerLevel));c.danger=dangerMultiplier(c.dangerLevel);c.negotiationPercent=std::max(EscortConfig::NegotiationMinPercent,std::min(EscortConfig::NegotiationMaxPercent,pct));c.reward=MercRewardBreakdown();if(c.type==MCT_CARAVAN){c.reward.base=EscortConfig::CaravanBase;c.reward.distance=(int)(c.distanceKm*EscortConfig::CaravanPerKm);c.reward.mission=caravanSizeBonus(c.caravanSize)+cargoBonus(c.cargoClass);}else if(c.type==MCT_SCIENCE){c.reward.base=EscortConfig::ScienceBase;c.reward.distance=(int)(c.distanceKm*EscortConfig::SciencePerKm);c.reward.mission=studyBonus(c.studyClass)+studyDurationBonus(c.studyDuration);}else if(c.type==MCT_MAIL){c.reward.base=EscortConfig::MailBase;c.reward.distance=(int)(c.distanceKm*EscortConfig::MailPerKm);c.reward.mission=c.urgent?(c.reward.base+c.reward.distance)/3:0;}else{c.reward.base=EscortConfig::EscortBase;c.reward.distance=(int)(c.distanceKm*EscortConfig::EscortPerKm);c.reward.mission=clientImportance(c.wealth);}c.reward.environment=environmentalBonus(c.environmentTags);c.reward.beforeDanger=c.reward.base+c.reward.distance+c.reward.mission+c.reward.environment;c.reward.afterDanger=(int)(c.reward.beforeDanger*c.danger+.5f);c.reward.afterRarity=(int)(c.reward.afterDanger*rarityMultiplier(c.rarity)+.5f);c.reward.guildHouseBonus=c.source==MCS_GUILD_HOUSE?c.reward.afterRarity*EscortConfig::GuildHouseBonusPercent/100:0;c.reward.beforeNegotiation=c.reward.afterRarity+c.reward.guildHouseBonus;c.reward.negotiation=c.reward.beforeNegotiation*c.negotiationPercent/100;c.reward.finalBeforeMissionBonuses=std::max(minimumFor(c.type),cap(c.reward.beforeNegotiation+c.reward.negotiation));c.basePay=c.reward.beforeNegotiation;c.totalPay=c.reward.finalBeforeMissionBonuses;c.finalPay=c.totalPay-c.advance;c.initialRate=c.distanceKm>0?c.basePay/c.distanceKm:0;c.negotiatedRate=c.distanceKm>0?c.totalPay/c.distanceKm:0;}
inline int bonusValue(EscortBonus b,int base,float d){switch(b){case EB_HEALTHY:return base/5;case EB_HALF_NOW:return 0;case EB_FAST:return base/6;case EB_NO_KO:return base/7;case EB_DANGER:return(int)(base*.10f*d);case EB_SUPPLIES:return std::min(1500,std::max(250,base/12));default:return 0;}}inline int calculateBonusTotal(int flags,int base,float d){int total=0;const EscortBonus all[]={EB_HEALTHY,EB_HALF_NOW,EB_FAST,EB_NO_KO,EB_DANGER,EB_SUPPLIES};for(int i=0;i<6;++i)if(flags&all[i])total+=bonusValue(all[i],base,d);return total;}
inline float wealthFactor(EscortClientWealth w){static const float v[]={.78f,1,1.18f,1.38f,1.65f};return v[(int)w];}inline float personalityBudget(EscortClientPersonality p){static const float v[]={1.50f,1.30f,1.12f,1.07f};return v[(int)p];}inline float acceptance(int pct,int bonuses,float local,float global,EscortClientWealth w,EscortClientPersonality p,float danger,bool prestige){float chance=pct<=0?1.0f:.96f-pct*.022f;chance-=bonuses*.055f;chance+=local*.003f+global*.002f;chance+=(wealthFactor(w)-1)*.20f;chance+=(personalityBudget(p)-1.2f)*.20f;chance+=(danger-1)*.03f+(prestige?.05f:0);return std::max(.03f,std::min(chance,.97f));}
inline int initialPay(float km,float danger,float,float,EscortClientWealth wealth,bool prestige,int groupSize,int cargoValue,bool urgent){EscortContractData c;c.type=MCT_ESCORT;c.distanceKm=km;c.dangerLevel=danger>=1.8f?5:danger>=1.48f?4:danger>=1.25f?3:danger>=1.08f?2:1;c.wealth=wealth;c.groupSize=groupSize;c.cargoValue=cargoValue;c.rarity=prestige?MCR_RARE:MCR_COMMON;c.urgent=urgent;calculate(c,0);return c.totalPay;}
}
