#include <cassert>
#include <iostream>
#include <map>
#include "src/EscortContract.h"
#include "MailContracts.h"
#include "DelegatedMissionTiming.h"
#include "GuildContractHistory.h"
#include "GuildOverviewDataModel.h"
#include "src/Save/FiscalLedgerFormat.h"
struct TestHandle {std::string toString(){return "giver-id";}};
struct TestGiver {TestHandle getHandle(){return TestHandle();}std::string getName(){return "Native giver";}} giver;
typedef TestGiver Character;TestGiver* contractBarman=&giver;Character* resolveContractBarman(){return contractBarman;}std::string currentMissionFiscalId="runtime-escort",originCity="Origin",destinationName="Target";
EscortContractData currentContract;int missionReward=30400;double currentGameHours=36,reportStartHour=36;
std::map<std::string,GuildHistory::Snapshot> contractSeeds;std::vector<std::string> contractHistory;
struct DelegatedMissionState {std::string groupId,offerIdentity,issuerIdentity,origin,destination;int kind,reward;DelegatedMissionTiming::State timing;};
#include "ContractSnapshotRuntime.h"
int main(){
 currentContract.type=MCT_SCIENCE;currentContract.dangerLevel=4;currentContract.destinationId="town";seedEscort();assert(contractHistory.empty()&&contractSeeds.size()==1);currentGameHours=39;missionReward=999;currentContract.dangerLevel=1;contractBarman=0;archiveEscort(1,0,0);assert(contractHistory.size()==1&&contractSeeds.empty());GuildHistory::Snapshot live;assert(GuildHistory::decode(contractHistory[0],live)&&live.reward==30400&&live.difficulty==4&&live.giverName=="Native giver"&&live.duration==3&&live.accepted==36);archiveEscort(1,0,0);assert(contractHistory.size()==1);
 MailContracts::Contract mail;mail.contractId="runtime-mail";mail.senderId="sender";mail.senderName="Merchant";mail.senderRole=MailContracts::RoleMerchant;mail.reward=500;mail.acceptedAtWorldHour=40;mail.urgent=true;mail.deadlineWorldHour=64;MailContracts::Step step;step.townId="town1";step.townName="First";mail.steps.push_back(step);step.townId="town2";step.townName="Second";mail.steps.push_back(step);archiveMail(mail,4);assert(GuildHistory::decode(contractHistory[0],live)&&live.status==4&&live.type=="mail_multi"&&live.routeIds=="town1\ntown2"&&live.deadline==64&&live.difficulty==-1);archiveMail(mail,4);assert(contractHistory.size()==2);
 DelegatedMissionState delegated;delegated.groupId="group";delegated.offerIdentity="offer";delegated.kind=2;delegated.reward=7000;delegated.timing=DelegatedMissionTiming::start(DelegatedMissionTiming::ActivityBountyHunt,20,40);archiveDelegated(delegated,2);assert(GuildHistory::decode(contractHistory[0],live)&&live.status==2&&live.type=="bounty"&&live.giver==2&&live.estimateMax>=live.estimateMin);

 GuildHistory::Snapshot s;s.id="contract-42";s.type="science";s.giver=1;s.giverId="native-handle";s.giverName="Name | special";s.origin="Origin";s.destination="Destination";s.destinationId="town-sid";s.reward=30400;s.bonusReward=0;s.difficulty=4;s.accepted=36.7;s.completed=37;s.duration=.3;s.status=1;s.bonus=0;
 std::vector<std::string> history;assert(GuildHistory::append(history,s));assert(!GuildHistory::append(history,s));GuildHistory::Snapshot copy;assert(GuildHistory::decode(history[0],copy));assert(GuildHistory::encode(copy)==GuildHistory::encode(s));assert(copy.giverName==s.giverName&&copy.reward==30400&&copy.difficulty==4&&copy.destinationId=="town-sid");assert(GuildHistory::parse(history[0]).status==1);s.status=4;s.id="cancel";assert(GuildHistory::append(history,s));assert(GuildHistory::parse(history[0]).status==2);s.status=2;s.id="failed";assert(GuildHistory::append(history,s));s.status=0;s.id="accepted";assert(GuildHistory::decode(GuildHistory::encode(s),copy)&&copy.status==0);assert(!GuildHistory::decode("@contract1 broken",copy));GuildHistory::Summary legacy=GuildHistory::parse("Origin -> Destination : REUSSI - SANS PRIME");assert(legacy.reward==-1&&legacy.bonus==0&&legacy.status==1);
 FiscalLedger ledger;ledger.recordInvestment(110000,35.957);ledger.cash.baseline(877200,36.033333778381348);ledger.cash.record(27964,905164,36.665634,Finance::Contract,"finance.contract");ledger.cash.record(30400,935564,36.77855,Finance::Contract,"finance.contract");ledger.cash.record(24917,960481,37.16872,Finance::Contract,"finance.contract");ledger.organisations[1].debt=8328;
 std::ostringstream saved;FiscalLedgerFormat::write(saved,ledger);FiscalLedger loaded;std::istringstream input(saved.str());FiscalLedgerFormat::read(input,loaded);assert(loaded.cash.entries.size()==4&&!loaded.cash.observed);assert(loaded.cash.entries.back().balance==-1);Finance::Summary summary=Finance::summary(loaded.cash,37.17,7);assert(summary.totals.income==83281&&summary.totals.expense==110000&&summary.totals.out[Finance::Investment]==110000&&summary.totals.out[Finance::Tax]==0);
 for(int pass=0;pass<5;++pass){std::ostringstream out;FiscalLedgerFormat::write(out,loaded);std::istringstream in(out.str());FiscalLedgerFormat::read(in,loaded);assert(loaded.cash.entries.size()==4&&loaded.organisations[1].debt==8328);for(int period=7;period<=90;period=period==7?30:period==30?90:91){Finance::Summary a=Finance::summary(loaded.cash,37.17,period);assert(a.totals.income==83281&&a.totals.expense==110000);}GuildOverview::Finances overview=GuildOverview::finances(loaded.cash,37.17);assert(overview.income==summary.totals.income&&overview.expense==summary.totals.expense);for(int d=0;d<7;++d){assert(overview.days[0][d]==summary.income[d]&&overview.days[1][d]==-summary.expense[d]&&overview.days[2][d]==summary.net[d]);}}
 // Fiscal text rounds timestamps: a first contemporary investment must not migrate twice.
 FiscalLedger first;first.cash.baseline(100000,35.957234);first.recordInvestment(1000,35.957234);first.cash.record(-1000,99000,35.957234,Finance::Investment,"finance.investment");std::ostringstream firstOut;FiscalLedgerFormat::write(firstOut,first);std::istringstream firstIn(firstOut.str());FiscalLedgerFormat::read(firstIn,first);assert(first.cash.entries.size()==1&&first.cash.totals(36,7).expense==1000);
 Finance::Journal empty;assert(Finance::summary(empty,100,7).totals.income==0);Finance::Journal windows;windows.record(5,5,24*3,Finance::Contract,"finance.contract");windows.record(-2,3,24*9,Finance::Investment,"finance.investment");assert(Finance::summary(windows,24*9,7).totals.income==5);assert(Finance::summary(windows,24*10,7).totals.income==0);
 std::cout<<"PASS Alpha: snapshot roundtrip, pending/completed/failed/cancelled, immutable legacy unknowns, ID deduplication, certified 110000 migration, 8328 unpaid debt excluded, repeated save/load, timestamp precision, shared 7/30/90 calendar windows and graph data.\n";
}
