// Phase 1: the overview reads the existing guard model; no simulation rules live here.
MyGUI::ImageBox* overviewImage(MyGUI::Widget* p,const char* texture,int x,int y,int w,int h){MyGUI::ImageBox* image=p->createWidget<MyGUI::ImageBox>("ImageBox",x,y,w,h,MyGUI::Align::Default);image->setImageTexture(texture);image->setNeedMouseFocus(false);return image;}
void guardIcon(MyGUI::Widget* p,int slot,int x,int y,int size,const MyGUI::Colour& colour){MyGUI::ImageBox* i=overviewImage(p,"MercenarieGuardOverviewIcons.png",x,y,size,size);i->setImageCoord(MyGUI::IntCoord(slot*64,0,64,64));i->setColour(colour);}
MyGUI::TextBox* overviewLabel(MyGUI::Widget* p,int x,int y,int w,int h,const std::string& value,const MyGUI::Colour& colour,int font=0){MyGUI::TextBox* t=registerText(p,x,y,w,h,font?font:uiFont,value,colour);fitLine(t);if(font)t->setFontHeight(font);return t;}
MyGUI::Button* overviewAction(MyGUI::Widget* p,int x,int y,int w,int h,const char* key,const std::string& action){MyGUI::Button* b=button(p,x,y,w,Loc::text(key),action);b->setSize(w,h);setButtonText(b,Loc::text(key));return b;}
MyGUI::Widget* overviewBox(MyGUI::Widget* p,int x,int y,int w,int h,const char* key,int pad,int title){MyGUI::Widget* b=p->createWidget<MyGUI::Widget>("MercenarieOverviewPanel",x,y,w,h,MyGUI::Align::Default);overviewLabel(b,pad,4,w-2*pad,title-6,Loc::text(key),registerIvory);registerSolid(b,pad,title,w-2*pad,1,registerAmber);return b;}
void overviewMetric(MyGUI::Widget* p,int y,int width,int height,int slot,const char* key,const MyGUI::Colour& colour,int pad){int size=std::min(height-6,std::max(24,uiFont*2));guardIcon(p,slot,pad,y+(height-size)/2,size,colour);int x=pad+size+pad,w=width-x-pad;liveLabels[key]=overviewLabel(p,x,y,w,uiFont+7,"0",registerIvory,uiFont+2);MyGUI::TextBox* caption=registerText(p,x,y+uiFont+7,w,std::max(uiFont+3,height-uiFont-7),uiFont,Loc::text((std::string("guards.")+key).c_str()),registerIvory);fitLine(caption);}
void buildOverview(MyGUI::Widget* p,int w,int h){
 uiFont=std::max(12,std::min(22,(int)(16*std::min(w/1100.,h/660.))));int pad=std::max(6,w/140),gap=std::max(6,w/180),header=std::max(56,h*12/100),nav=std::max(28,h*6/100),footer=std::max(24,h*5/100),banner=std::max(70,h*20/100),bh=std::max(30,std::min(50,h/14));
 int logo=header-2*pad;MyGUI::ImageBox* sun=overviewImage(p,"MercenarieOverviewIcons.png",pad,pad,logo,logo);sun->setImageCoord(MyGUI::IntCoord(0,0,128,128));sun->setColour(registerAmber);
 int tx=logo+3*pad,quote=w>=1000?w/5:0,tw=w-tx-quote-pad;
 MyGUI::TextBox* title=overviewLabel(p,tx,pad,tw,header/2-pad,std::string(Loc::text("ui.the_mercenarie"))+" | "+Loc::text("guards.management"),registerIvory);fitRegisterText(title,std::max(17,uiFont+5));
 MyGUI::TextBox* subtitle=registerText(p,tx,header/2,tw,header/2-pad,uiFont,Loc::text("guards.overview_subtitle"),registerIvory);fitRegisterText(subtitle,uiFont);
 if(quote){MyGUI::TextBox* q=registerText(p,w-quote,pad,quote-pad,header-2*pad,uiFont-1,Loc::text("guards.overview_quote"),MyGUI::Colour(.64f,.65f,.63f));fitRegisterText(q,uiFont-1);}
 registerSolid(p,pad,header,w-2*pad,1,registerAmber);
 const char* tabs[]={"guards.overview","guards.title","guards.posts","guards.tags"};int tabW=(w*70/100-3*gap)/4;for(int n=0;n<4;++n)overviewAction(p,pad+n*(tabW+gap),header+gap,tabW,nav,tabs[n],"tab:"+number(n))->setStateSelected(n==0);
 int top=header+gap+nav+gap,contentH=h-top-banner-footer-3*gap,total=w-2*pad;
 int widths[4]={total*24/100,total*22/100,total*20/100,0};widths[3]=total-widths[0]-widths[1]-widths[2]-3*gap;int x=pad,titleH=uiFont+12;
 MyGUI::Widget* a=overviewBox(p,x,top,widths[0],contentH,"guards.summary",pad,titleH);int row=(contentH-titleH-pad)/5;const char* keys[]={"total","serving","moving","resting_count","paused_count"};MyGUI::Colour colours[]={registerIvory,MyGUI::Colour(.39f,.72f,.25f),registerAmber,registerAmber,MyGUI::Colour(.59f,.53f,.81f)};for(int n=0;n<5;++n)overviewMetric(a,titleH+4+n*row,widths[0],row,n,keys[n],colours[n],pad);
 x+=widths[0]+gap;MyGUI::Widget* b=overviewBox(p,x,top,widths[1],contentH,"guards.posts",pad,titleH);overviewMetric(b,titleH+pad,widths[1],std::max(40,row+8),5,"post_total",registerAmber,pad);
 int barY=titleH+pad+std::max(40,row+8)+gap,barH=std::max(12,uiFont);registerSolid(b,pad,barY,widths[1]-2*pad,barH,MyGUI::Colour(.30f,.34f,.34f));registerSolid(b,pad+1,barY+1,widths[1]-2*pad-2,barH-2,MyGUI::Colour(.04f,.07f,.07f));overviewOccupancyWidth=widths[1]-2*pad-4;overviewOccupancy=registerSolid(b,pad+2,barY+2,overviewOccupancyWidth,barH-4,colours[1]);
 const char* states[]={"occupied","free"};for(int n=0;n<2;++n){int y=barY+barH+gap+n*(uiFont+8);registerSolid(b,pad,y+3,uiFont,uiFont,n?MyGUI::Colour(.45f,.50f,.52f):colours[1]);liveLabels[states[n]]=overviewLabel(b,pad+uiFont+6,y,uiFont*2,uiFont+5,"0",registerIvory);overviewLabel(b,pad+uiFont*3+8,y,widths[1]-2*pad-uiFont*3-8,uiFont+5,Loc::text((std::string("guards.")+states[n]).c_str()),registerIvory);}
 overviewAction(b,pad,contentH-bh-pad,widths[1]-2*pad,bh,"guards.view_posts","tab:2");
 x+=widths[1]+gap;MyGUI::Widget* c=overviewBox(p,x,top,widths[2],contentH,"guards.tags",pad,titleH);overviewMetric(c,titleH+pad,widths[2],std::max(40,row+8),6,"active_tags",registerAmber,pad);int tagTop=barY,tagBottom=contentH-bh-2*pad;
 MyGUI::ScrollView* tags=c->createWidget<MyGUI::ScrollView>("TheMercenarie_ScrollView",pad,tagTop,widths[2]-2*pad,std::max(12,tagBottom-tagTop),MyGUI::Align::Default);tags->setVisibleHScroll(false);tags->setCanvasAlign(MyGUI::Align::Left|MyGUI::Align::Top);MercenarieNativeInput::bind(tags);int y=0,tagW=tags->getWidth()-18;
 for(std::map<GuildGuards::Id,GuildGuards::Tag>::const_iterator i=guildGuards.tags.begin();i!=guildGuards.tags.end();++i){if(i->second.paused)continue;unsigned count=0;for(std::map<GuildGuards::Id,GuildGuards::Post>::const_iterator j=guildGuards.posts.begin();j!=guildGuards.posts.end();++j)if(j->second.tag==i->first)++count;registerSolid(tags,0,y+4,8,8,colours[1]);overviewLabel(tags,12,y,std::max(1,tagW-45),uiFont+6,i->second.name,registerIvory);overviewLabel(tags,std::max(12,tagW-29),y,29,uiFont+6,number(count),registerIvory);y+=uiFont+10;}
 tags->setCanvasSize(tagW,std::max(1,y));overviewAction(c,pad,contentH-bh-pad,widths[2]-2*pad,bh,"guards.manage_tags","tab:3");
 x+=widths[2]+gap;MyGUI::Widget* d=overviewBox(p,x,top,widths[3],contentH,"guards.service",pad,titleH);MyGUI::ScrollView* rows=d->createWidget<MyGUI::ScrollView>("TheMercenarie_ScrollView",pad,titleH+gap,widths[3]-2*pad,contentH-titleH-gap-pad,MyGUI::Align::Default);rows->setVisibleHScroll(false);rows->setCanvasAlign(MyGUI::Align::Left|MyGUI::Align::Top);MercenarieNativeInput::bind(rows);int rw=rows->getWidth()-18,rh=std::max(32,(contentH-titleH-gap-pad)/6),icon=std::min(30,rh-6),nameW=(rw-icon-gap)*31/100,stateW=(rw-icon-gap)*34/100,postW=rw-icon-gap-nameW-stateW;y=0;
 for(std::map<std::string,GuildGuards::Guard>::const_iterator i=guildGuards.guards.begin();i!=guildGuards.guards.end();++i){guardIcon(rows,1,0,y+(rh-icon)/2,icon,registerIvory);MyGUI::Button* pick=overviewAction(rows,icon+gap,y,nameW,rh-2,"guards.people","guard:"+i->first);setButtonText(pick,i->second.name);int sx=icon+gap+nameW;statusLabels[i->first]=overviewLabel(rows,sx,y+(rh-uiFont-4)/2,stateW,uiFont+4,Loc::text(stateKey(guardState(i->second))),stateColour(guardState(i->second)));liveLabels["post/"+i->first]=overviewLabel(rows,sx+stateW,y+(rh-uiFont-4)/2,postW,uiFont+4,postName(i->second),registerIvory);registerSolid(rows,0,y+rh-1,rw,1,MyGUI::Colour(.13f,.17f,.17f));y+=rh;}
 if(y==0)overviewLabel(rows,0,0,rw,uiFont+4,Loc::text("guards.overview_empty"),registerIvory);rows->setCanvasSize(rw,std::max(1,y));
 int bannerY=top+contentH+gap;MyGUI::ImageBox* art=overviewImage(p,"GuildDashboardHero.png",pad,bannerY,total,banner);int cropH=std::min(724,2172*banner/std::max(1,total));art->setImageCoord(MyGUI::IntCoord(0,std::max(0,(724-cropH)/2),2172,cropH));
 MyGUI::Widget* shade=registerSolid(p,pad,bannerY,total*56/100,banner,MyGUI::Colour(.02f,.03f,.03f));shade->setAlpha(.56f);
 MyGUI::TextBox* motto=registerText(p,pad*3,bannerY+banner/4,total*48/100, banner/2,uiFont+1,Loc::text("guards.overview_motto"),registerIvory);fitRegisterText(motto,uiFont+1);
 overviewAction(p,pad+total*59/100,bannerY+(banner-bh)/2,total*39/100,bh,preview?"guards.preview_off":"guards.overview_world","preview");
 int fy=h-footer;registerSolid(p,pad,fy,total,1,registerAmber);overviewLabel(p,pad,fy+3,total/4,footer-5,Loc::text("ui.the_mercenarie"),registerAmber);overviewLabel(p,pad+total/4,fy+3,total/2,footer-5,Loc::text("guards.overview_footer"),registerAmber);overviewAction(p,w-pad-total/6,fy+2,total/6,footer-3,"guards.close_window","close");
}
