// Presentation only: office registry, furniture, fiscal ledger and faction API
// remain the authoritative data. Nothing here changes the save format.
std::string gpText(const char* key){return Loc::text((std::string("guild.pages.")+key).c_str());}
GuildPages::Layout goLayout,grLayout;
bool go101Creating=true;MyGUI::Widget* go101Guide=0;MyGUI::TextBox *go101Title=0,*go101Next=0,*go101Checks=0;void go101Update();
std::string goSelected,grSelected,goSignature,grSignature;
unsigned long goLast=0,grLast=0;
MyGUI::ScrollView *goList=0,*goDetails=0,*grList=0,*grDetails=0;
MyGUI::TextBox *goCount=0,*goDetail=0,*goEmpty=0,*goReason=0,*grDetail=0,*grEmpty=0;
MyGUI::Button *goCreate=0,*goManage=0,*go102Add=0;
MyGUI::ImageBox* goMap=0;
MyGUI::Widget *grDetailTrack=0,*grDetailFill=0;
MyGUI::TextBox *goHeroName=0,*goHeroStatus=0,*grHeroName=0,*grHeroStatus=0;
GuildMapViewport::Crop goCrop={0,0,2048,2048};int goDragX=0,goDragY=0;bool goMapFitted=false;
struct GPCard {MyGUI::ImageBox* icon;MyGUI::Button* action;MyGUI::Button* button;MyGUI::TextBox *name,*status,*value,*city,*note,*actionText;MyGUI::Widget* badge;MyGUI::Widget *track,*fill;};
std::vector<GPCard> goCards,grCards;
struct GOMarker {MyGUI::Button* button;std::string key;float x,y;};
std::vector<GOMarker> goMarkers;
struct GOOffice {std::string key,name,city,territory;bool active,known,client,waiting;float x,y;bool position;GOOffice():active(false),known(false),client(false),waiting(false),x(0),y(0),position(false){}};
struct GRFaction {std::string key,name;float value;bool ally,enemy;};
std::vector<GOOffice> goOffices;std::vector<GRFaction> grFactions;
void resetGuildPages(){go101Guide=0;go101Title=go101Next=go101Checks=0;go101Creating=true;goList=goDetails=grList=grDetails=0;goCount=goDetail=goEmpty=goReason=grDetail=grEmpty=0;goCreate=goManage=go102Add=0;goMap=0;goHeroName=goHeroStatus=grHeroName=grHeroStatus=0;grDetailTrack=grDetailFill=0;goCards.clear();grCards.clear();goMarkers.clear();goOffices.clear();grFactions.clear();goSelected.clear();grSelected.clear();goSignature.clear();grSignature.clear();goLast=grLast=0;goMapFitted=false;goCrop=GuildMapViewport::clamp(0,0,2048,1,1);}
MyGUI::Colour gpColour(bool positive,bool negative){return positive?registerGreen:negative?MyGUI::Colour(.85f,.25f,.16f):registerIvory;}
void gpScrollText(MyGUI::ScrollView* scroll,MyGUI::TextBox* text,const std::string& content,int font){MercenarieFonts::caption(text,gcWrap(text,content,font));text->setFontHeight(font);text->setSize(text->getWidth(),std::max(font+4,text->getTextSize().height+font));scroll->setCanvasSize(text->getWidth()+6,std::max(scroll->getHeight()-4,text->getHeight()+4));}
MyGUI::ScrollView* gpScroll(MyGUI::Widget* parent,int x,int y,int w,int h){MyGUI::ScrollView* s=parent->createWidget<MyGUI::ScrollView>("Kenshi_ScrollViewEmpty",x,y,w,h,MyGUI::Align::Default);MercenarieNativeInput::bind(s);s->setVisibleHScroll(false);s->setCanvasAlign(MyGUI::Align::Left|MyGUI::Align::Top);return s;}
MyGUI::ImageBox* gpSymbol(MyGUI::Widget* p,int id,int x,int y,int size,const MyGUI::Colour& colour){MyGUI::ImageBox* icon=registerTextureIcon(p,"MercenarieGuildSymbols.png",x,y,size,colour);icon->setImageCoord(MyGUI::IntCoord(id*128,0,128,128));return icon;}
MyGUI::Button* gpButton(MyGUI::Widget* p,int x,int y,int w,int h,const char* skin="MercenarieGuildRow"){return p->createWidget<MyGUI::Button>(skin,x,y,w,h,MyGUI::Align::Default);}
TownBase* goTown(const std::string& city){if(!shou||!shou->townList)return 0;lektor<RootObject*>& towns=shou->townList->getAllTowns();for(unsigned int i=0;i<towns.size();++i){TownBase* town=dynamic_cast<TownBase*>(towns[i]);if(town&&town->isTown()&&ReputationIdentity::key(frenchPlaceName(town->getName()))==ReputationIdentity::key(city))return town;}return 0;}
Building* goBuilding(const std::string& key,const std::string& city){if(!ou||!ou->zoneMgr||!ou->player)return 0;Building* active=designatedGuildHouseHandle.isNull()?0:designatedGuildHouseHandle.getBuilding();if(active&&!active->isDestroyed()&&active->isThePlayer()&&guildHouseKey(active)==key)return active;TownBase* town=goTown(city);if(!town)return 0;lektor<Building*> buildings;ou->zoneMgr->findAllBuildings(buildings,town,ou->player->getFaction(),false,0,0);for(unsigned int i=0;i<buildings.size();++i)if(buildings[i]&&!buildings[i]->isDestroyed()&&buildings[i]->isThePlayer()&&guildHouseKey(buildings[i])==key)return buildings[i];return 0;}
std::vector<GOOffice> goCollect(){std::vector<GOOffice> rows;
 for(std::map<std::string,std::string>::const_iterator it=guildHouseNames.begin();it!=guildHouseNames.end();++it){GOOffice r;r.key=it->first;r.name=it->second;r.city=guildHouseCities.count(r.key)?guildHouseCities.find(r.key)->second:gpText("unavailable");r.active=r.key==designatedGuildHouseKey;r.territory=gpText("unavailable");
  // Existing scanner covers interior furniture including editor-placed chairs.
  // It only certifies the active office; remote offices must remain unknown.
  r.known=r.active&&guildBuilding;r.client=r.known&&guildClientChair;r.waiting=r.known&&!guildWaitingChairs.empty();
  TownBase* town=goTown(r.city);if(town&&ou&&ou->zoneMgr){iVector2 sector=ou->zoneMgr->getMapSector(town->getPosition());r.x=(sector.x+.5f)*32.f;r.y=(sector.y+.5f)*32.f;r.position=true;Faction* owner=town->getFaction();if(owner&&owner->getData())r.territory=mercenarieLocalize(owner->getData()->name);}
  rows.push_back(r);
 }return rows;}
std::string goCreationReason(){if(guildLevel()<3)return gpText("level3");if((int)guildHouseNames.size()>=GuildProgression::officeLimit(guildLevel()))return gpText("limit");Building* selected=selectedPlayerBuilding();if(!selected)return gpText("select_building");if(guildHouseNames.count(guildHouseKey(selected)))return gpText("registered");TownBase* town=selected->getCurrentTownLocation();if(!town||!town->isTown())return gpText("invalid_city");std::string city=ReputationIdentity::key(frenchPlaceName(town->getName()));for(std::map<std::string,std::string>::const_iterator i=guildHouseCities.begin();i!=guildHouseCities.end();++i)if(guildHouseNames.count(i->first)&&ReputationIdentity::key(i->second)==city)return gpText("occupied");return "";}
void refreshOfficesView(bool force=false);
void goSelect(MyGUI::Widget* sender){if(!goList||!sender)return;for(size_t i=0;i<goCards.size()&&i<goOffices.size();++i)if(sender==goCards[i].button){go101Creating=false;goSelected=goOffices[i].key;refreshOfficesView(true);return;}for(size_t i=0;i<goMarkers.size();++i)if(sender==goMarkers[i].button){go101Creating=false;goSelected=goMarkers[i].key;refreshOfficesView(true);return;}}
void goManageClick(MyGUI::Widget*);
void goManageRow(MyGUI::Widget* sender){for(size_t i=goOffices.size();i<goCards.size();++i)if(sender==goCards[i].action&&i<(size_t)GuildProgression::officeLimit(guildLevel())){go101Creating=true;goSelected.clear();refreshOfficesView(true);return;}for(size_t i=0;i<goCards.size()&&i<goOffices.size();++i)if(goCards[i].action==sender){goSelected=goOffices[i].key;goManageClick(0);return;}}
void goCreateClick(MyGUI::Widget*){if(!goList)return;if(!selectedPlayerBuilding()){if(guildWindow)guildWindow->setVisible(false);if(ou)ou->showPlayerAMessage(gpText("select_building"),true);return;}if(goCreationReason().empty())defineGuildHouseClicked(0);refreshOfficesView(true);}
void go101New(MyGUI::Widget*){if((int)guildHouseNames.size()>=GuildProgression::officeLimit(guildLevel()))return;go101Creating=true;goSelected.clear();refreshOfficesView(true);}
void goManageClick(MyGUI::Widget*){if(!goList)return;for(size_t i=0;i<goOffices.size();++i)if(goOffices[i].key==goSelected){Building* b=goBuilding(goSelected,goOffices[i].city);if(!b)return;pendingGuildHouseKey=goSelected;pendingGuildHouseHandle=b;requestGuildOfficeManagement();return;}}
void goRefreshMap(){if(!goMap)return;goCrop=GuildMapViewport::clamp(goCrop.x,goCrop.y,goCrop.w,goMap->getWidth(),goMap->getHeight());goMap->setImageTexture("GuildEscortMap.png");goMap->setImageCoord(MyGUI::IntCoord(goCrop.x,goCrop.y,goCrop.w,goCrop.h));for(size_t i=0;i<goMarkers.size();++i){GOMarker& m=goMarkers[i];int x=int((m.x-goCrop.x)*goMap->getWidth()/goCrop.w),y=int((m.y-goCrop.y)*goMap->getHeight()/goCrop.h);m.button->setPosition(std::max(0,std::min(goMap->getWidth()-m.button->getWidth(),x-m.button->getWidth()/2)),std::max(0,std::min(goMap->getHeight()-m.button->getHeight(),y-m.button->getHeight()/2)));m.button->setVisible(x>=0&&y>=0&&x<goMap->getWidth()&&y<goMap->getHeight());m.button->setStateSelected(m.key==goSelected);}}
void goFitMap(){if(!goMap||goMarkers.empty())return;float x=0,y=0;for(size_t i=0;i<goMarkers.size();++i){x+=goMarkers[i].x;y+=goMarkers[i].y;}goCrop=GuildMapViewport::clamp(0,0,2048,goMap->getWidth(),goMap->getHeight());goCrop.x=int(x/goMarkers.size())-goCrop.w/2;goCrop.y=int(y/goMarkers.size())-goCrop.h/2;goRefreshMap();goMapFitted=true;}
void goWheel(MyGUI::Widget*,int rel){if(!goMap||!rel)return;int oldW=goCrop.w,oldH=goCrop.h;int width=oldW+(rel>0?-1:1)*std::max(64,oldW/8);GuildMapViewport::Crop next=GuildMapViewport::clamp(0,0,width,goMap->getWidth(),goMap->getHeight());goCrop=GuildMapViewport::clamp(goCrop.x+(oldW-next.w)/2,goCrop.y+(oldH-next.h)/2,next.w,goMap->getWidth(),goMap->getHeight());goRefreshMap();}
void goPress(MyGUI::Widget*,int x,int y,MyGUI::MouseButton button){if(button==MyGUI::MouseButton::Left){goDragX=x;goDragY=y;}}
void goDrag(MyGUI::Widget*,int x,int y,MyGUI::MouseButton button){if(!goMap||button!=MyGUI::MouseButton::Left)return;goCrop.x-=(x-goDragX)*goCrop.w/std::max(1,goMap->getWidth());goCrop.y-=(y-goDragY)*goCrop.h/std::max(1,goMap->getHeight());goDragX=x;goDragY=y;goRefreshMap();}
void goZoomIn(MyGUI::Widget*){goWheel(0,1);}void goZoomOut(MyGUI::Widget*){goWheel(0,-1);}
void refreshOfficesView(bool force){if(!goList)return;unsigned long now=GetTickCount();if(!force&&now-goLast<500)return;goLast=now;goOffices=goCollect();
 std::string reason=goCreationReason();std::stringstream signature;signature<<gMercenarieEnglish<<guildLevel()<<goSelected<<reason<<int(currentGameHours);
 for(size_t i=0;i<goOffices.size();++i){const GOOffice& r=goOffices[i];signature<<r.key<<r.name<<r.city<<r.territory<<r.active<<r.known<<r.client<<r.waiting<<r.position<<r.x<<r.y;}for(int o=0;o<2;++o)signature<<fiscalLedger.organisations[o].debt<<fiscalLedger.organisations[o].targetHouseId<<fiscalLedger.organisations[o].nextCollectionHour<<fiscalLedger.organisations[o].state;
 if(!force&&signature.str()==goSignature)return;goSignature=signature.str();bool found=false;if(!goOffices.empty()&&(int)goOffices.size()>=GuildProgression::officeLimit(guildLevel()))go101Creating=false;for(size_t i=0;i<goOffices.size();++i)if(goOffices[i].key==goSelected)found=true;if(go101Creating)goSelected.clear();else if(!found)goSelected=goOffices.empty()?"":goOffices[0].key;
 int font=goLayout.font,p=goLayout.pad,row=goLayout.row,width=goList->getWidth()-20;size_t slots=std::max(goOffices.size(),size_t(3));
 while(goCards.size()<slots){
  GPCard c={};c.button=goList->createWidget<MyGUI::Button>("Overview96Button",0,int(goCards.size())*(row+p/2),width,row,MyGUI::Align::Default);c.button->eventMouseButtonClick+=MyGUI::newDelegate(goSelect);
  registerSolid(c.button,0,0,width,1,o95Edge);registerSolid(c.button,0,row-1,width,1,o95Edge);registerSolid(c.button,0,0,1,row,o95Edge);registerSolid(c.button,width-1,0,1,row,o95Edge);
  c.icon=gpSymbol(c.button,0,op95(16),op95(12),op95(40),o95Gold);c.name=ot95(c.button,78,3,430,28,"",23);c.city=ot95(c.button,78,32,450,25,"",17);c.note=ot95(c.button,78,62,450,18,"",13);c.note->setVisible(false);c.status=ot95(c.button,566,5,165,23,"",15,true);c.action=ob95(c.button,566,28,165,31,"");c.actionText=ot95(c.action,2,0,161,31,"",17,true);c.actionText->setTextAlign(MyGUI::Align::Center);c.action->eventMouseButtonClick+=MyGUI::newDelegate(goManageRow);goCards.push_back(c);
 }
 for(size_t i=0;i<goCards.size();++i){
  GPCard& c=goCards[i];c.button->setVisible(i<slots);if(i>=slots)continue;
  bool present=i<goOffices.size(),available=i<(size_t)GuildProgression::officeLimit(guildLevel());c.button->setEnabled(true);
  c.icon->setImageCoord(MyGUI::IntCoord((present||available?0:3)*128,0,128,128));c.icon->setColour(present||available?o95Gold:MyGUI::Colour(.40f,.41f,.39f));
  c.button->setStateSelected(present&&goOffices[i].key==goSelected);c.action->setVisible(true);
  gcCell(c.actionText,gpText(present?"manage_short":available?"available":"locked_short"),font);c.actionText->setTextColour(present?registerAmber:MyGUI::Colour(.48f,.48f,.44f));
  if(present){const GOOffice& r=goOffices[i];gcCell(c.name,r.name,font+2);gcCell(c.city,mercenarieLocalize(r.city),font);gcCell(c.note,r.territory,font);c.note->setTextColour(MyGUI::Colour(.61f,.62f,.56f));gcCell(c.status,gpText(r.active?"active_short":"secondary_short"),font);c.status->setTextColour(r.active?registerGreen:registerIvory);c.action->setEnabled(goBuilding(r.key,r.city)!=0);}
  else{gcCell(c.name,gpText(available?"available":"locked"),font);gcCell(c.city,gpText(available?"select_building":i==0?"level3":"level4"),font);MercenarieFonts::caption(c.note,"");MercenarieFonts::caption(c.status,"");c.action->setEnabled(available);}
 }
 goList->setCanvasSize(width,int(slots)*(row+p/2));goEmpty->setVisible(false);MercenarieFonts::caption(goCount,gpText("your_offices")+" ("+registerNumber(goOffices.size())+" / "+registerNumber(GuildProgression::officeLimit(guildLevel()))+")");goCreate->setEnabled(reason.empty());gcCell(goReason,reason.empty()?gpText("ready"):reason,font);
 MercenarieFonts::caption(goHeroName,"");MercenarieFonts::caption(goHeroStatus,"");std::stringstream detail;bool manageable=false;for(size_t i=0;i<goOffices.size();++i)if(goOffices[i].key==goSelected){const GOOffice& r=goOffices[i];manageable=goBuilding(r.key,r.city)!=0;gcCell(goHeroName,r.name,font+2);gcCell(goHeroStatus,gpText(r.active?"active":"secondary"),font);goHeroStatus->setTextColour(r.active?registerGreen:registerIvory);detail<<gpText("location_section")<<"\n"<<gpText("city")<<" : "<<mercenarieLocalize(r.city)<<"\n"<<gpText("territory")<<" : "<<r.territory<<"\n"<<gpText("income")<<" : "<<gpText("not_tracked")<<"\n"<<"\n"<<gpText("equipment_section")<<"\n"<<gpText("client_chair")<<" : "<<gpText(!r.known?"unavailable":r.client?"installed":"missing")<<"\n"<<gpText("waiting_chair")<<" : "<<gpText(!r.known?"unavailable":r.waiting?"installed":"missing");
  bool fiscal=false;for(int o=0;o<2;++o){const FiscalOrganisationState& s=fiscalLedger.organisations[o];if(s.targetHouseId!=r.key)continue;fiscal=true;detail<<"\n\n"<<mercenarieLocalize(fiscalOrgName((FiscalOrganisation)o))<<"\n"<<gpText("taxes")<<" : "<<registerNumber(s.debt)<<" Cats"<<"\n"<<gpText("collection_state")<<" : "<<mercenarieLocalize(fiscalStateName(s.state));if(s.debt>0&&s.nextCollectionHour>currentGameHours)detail<<"\n"<<gpText("remaining")<<" : "<<(int)ceil(s.nextCollectionHour-currentGameHours)<<" h";}
  if(!fiscal)detail<<"\n"<<gpText("taxes")<<" : "<<gpText("no_target");detail<<"\n\n"<<gpText("manage_help_short");}
 gpScrollText(goDetails,goDetail,goSelected.empty()?gpText("no_office"):detail.str(),font);goManage->setEnabled(manageable);
 // Reuse marker widgets, and never fabricate positions for unresolved towns.
 size_t m=0;for(size_t i=0;i<goOffices.size();++i){const GOOffice& r=goOffices[i];if(!r.position)continue;if(m==goMarkers.size()){GOMarker marker;marker.button=gpButton(goMap,0,0,std::max(120,9*font),2*font,"MercenarieGuildMarker");gpSymbol(marker.button,2,3,3,2*font-6,registerAmber);overviewText(marker.button,2*font,0,7*font-4,2*font,font,"");marker.button->eventMouseButtonClick+=MyGUI::newDelegate(goSelect);marker.button->eventMouseWheel+=MyGUI::newDelegate(goWheel);marker.button->eventMouseButtonPressed+=MyGUI::newDelegate(goPress);marker.button->eventMouseDrag+=MyGUI::newDelegate(goDrag);goMarkers.push_back(marker);}GOMarker& marker=goMarkers[m++];marker.key=r.key;marker.x=r.x;marker.y=r.y;MyGUI::TextBox* label=marker.button->getChildAt(1)->castType<MyGUI::TextBox>();std::string city=mercenarieLocalize(r.city);int markerW=std::min(goMap->getWidth()-op95(16),std::max(op95(230),std::min(op95(390),op95(48)+(int)city.size()*op95(10))));marker.button->setSize(markerW,op95(32));label->setCoord(op95(34),0,markerW-op95(40),op95(32));label->setNeedMouseFocus(false);o95Caption(label,city,18);}
 go101Update();
 while(goMarkers.size()>m){mercenarieDestroyLiveWidget(goMarkers.back().button);goMarkers.pop_back();}if(!goMapFitted&&!goMarkers.empty())goFitMap();else goRefreshMap();
}
bool grLess(const GRFaction& a,const GRFaction& b){return a.name==b.name?a.key<b.key:a.name<b.name;}
std::vector<GRFaction> grCollect(){std::vector<GRFaction> rows;if(!ou||!ou->player||!ou->player->participant||!ou->factionMgr)return rows;const lektor<Faction*>* factions=ou->factionMgr->getAllFactions();if(!factions)return rows;for(unsigned int i=0;i<factions->size();++i){Faction* f=(*factions)[i];if(!f||f==ou->player->participant||f==ou->factionMgr->getEmptyFaction()||!f->relations||!f->getData()||f->getData()->name.empty())continue;GRFaction r;r.key=f->getData()->stringID;r.name=mercenarieLocalize(f->getData()->name);r.value=f->relations->getFactionRelation(ou->player->participant);r.ally=f->relations->isAlly(ou->player->participant);r.enemy=f->relations->isEnemy(ou->player->participant);rows.push_back(r);}std::sort(rows.begin(),rows.end(),grLess);return rows;}
std::string grStanding(const GRFaction& r){return gpText(r.ally?"ally":r.enemy?"hostile":"neutral");}
void grBar(MyGUI::Widget* track,MyGUI::Widget* fill,float value,const MyGUI::Colour& colour){GuildPages::Bar b=GuildPages::signedBar(value,track->getWidth()-4);fill->setCoord(2+b.x,2,std::max(1,b.width),std::max(1,track->getHeight()-4));fill->setVisible(b.width>0);fill->setColour(colour);}
void refreshFactionView(bool force=false);
void grSelect(MyGUI::Widget* sender){if(!grList||!sender)return;for(size_t i=0;i<grCards.size()&&i<grFactions.size();++i)if(sender==grCards[i].button){grSelected=grFactions[i].key;refreshFactionView(true);return;}}
void refreshFactionView(bool force){if(!grList)return;unsigned long now=GetTickCount();if(!force&&now-grLast<500)return;grLast=now;grFactions=grCollect();std::stringstream signature;signature<<gMercenarieEnglish<<grSelected;for(size_t i=0;i<grFactions.size();++i)signature<<grFactions[i].key<<grFactions[i].name<<grFactions[i].value<<grFactions[i].ally<<grFactions[i].enemy;if(!force&&signature.str()==grSignature)return;grSignature=signature.str();bool found=false;for(size_t i=0;i<grFactions.size();++i)if(grFactions[i].key==grSelected)found=true;if(!found)grSelected=grFactions.empty()?"":grFactions[0].key;
 int f=grLayout.font,p=grLayout.pad,row=grLayout.row,w=grList->getWidth()-20;
 while(grCards.size()<grFactions.size()){
  GPCard c={};c.button=gpButton(grList,0,int(grCards.size())*row,w,row-2);c.button->eventMouseButtonClick+=MyGUI::newDelegate(grSelect);c.icon=gpSymbol(c.button,1,4,5,row-12,registerIvory);
  int nameX=row;c.name=overviewText(c.button,nameX,2,w*40/100-nameX,row-6,f,"");
  c.badge=c.button->createWidget<MyGUI::Widget>("MercenarieGuildBadge",w*41/100,5,w*20/100,row-12,MyGUI::Align::Default);c.badge->setNeedMouseFocus(false);
  c.status=overviewText(c.badge,3,1,c.badge->getWidth()-6,c.badge->getHeight()-2,f,"");c.status->setTextAlign(MyGUI::Align::Center);
  c.value=overviewText(c.button,w*63/100,2,w*12/100,row-6,f,"");c.value->setTextAlign(MyGUI::Align::Center);
  overviewBar(c.button,w*77/100,row/2-7,w*21/100,14,c.track,c.fill);registerSolid(c.track,c.track->getWidth()/2,0,1,14,registerIvory);grCards.push_back(c);
 }
 for(size_t i=0;i<grCards.size();++i){GPCard& c=grCards[i];c.button->setVisible(i<grFactions.size());if(i>=grFactions.size())continue;const GRFaction& r=grFactions[i];MyGUI::Colour colour=gpColour(r.ally||r.value>0,r.enemy||r.value<0);c.button->setStateSelected(r.key==grSelected);gcCell(c.name,r.name,f);gcCell(c.status,grStanding(r),f);std::stringstream value;value<<std::showpos<<std::fixed<<std::setprecision(1)<<r.value;gcCell(c.value,value.str(),f);c.status->setTextColour(gpColour(r.ally,r.enemy));c.icon->setColour(r.key==grSelected?registerAmber:registerIvory);c.value->setTextColour(colour);grBar(c.track,c.fill,r.value,colour);}
 grList->setCanvasSize(w,std::max(grList->getHeight()-4,int(grFactions.size())*row));grEmpty->setVisible(grFactions.empty());MercenarieFonts::caption(grHeroName,"");MercenarieFonts::caption(grHeroStatus,"");grDetailTrack->setVisible(!grFactions.empty());std::stringstream detail;for(size_t i=0;i<grFactions.size();++i)if(grFactions[i].key==grSelected){const GRFaction& r=grFactions[i];grBar(grDetailTrack,grDetailFill,r.value,gpColour(r.ally||r.value>0,r.enemy||r.value<0));gcCell(grHeroName,r.name,f+2);gcCell(grHeroStatus,grStanding(r),f);grHeroStatus->setTextColour(gpColour(r.ally,r.enemy));detail<<gpText("value")<<" : "<<std::fixed<<std::setprecision(1)<<r.value<<" / 100\n\n"<<gpText("effects")<<"\n"<<gpText("native_relations_short")<<"\n\n"<<gpText("improve")<<"\n"<<gpText("no_methods_short");}gpScrollText(grDetails,grDetail,grSelected.empty()?gpText("no_faction"):detail.str(),f);
}
void buildGuildOfficesReputation(MyGUI::Widget* parent){resetGuildPages();goLayout=GuildPages::calculate(overviewLayout,true);grLayout=GuildPages::calculate(overviewLayout,false);
 for(int page=1;page<2;++page){bool office=page==0;const GuildPages::Layout& l=office?goLayout:grLayout;int p=l.pad,f=l.font;MyGUI::Widget* root=overviewEmptyPanel(parent,l.page);if(office)guildOfficesPanel=root;else guildReputationPanel=root;
  MyGUI::Widget* heading=overviewPanel(root,l.heading);int buttonW=office?std::max(180,l.heading.w*26/100):0;overviewText(heading,p,2,l.heading.w-buttonW-2*p,2*f,f+6,gpText(office?"offices":"reputation"));overviewText(heading,p,2*f+3,l.heading.w-buttonW-2*p,l.heading.h-2*f-5,f,gpText(office?"office_subtitle":"rep_subtitle"));
  MyGUI::Widget* list=overviewSection(root,l.list,"");MyGUI::Widget* detail=overviewSection(root,l.details,gpText(office?"office_details":"faction_details"));MyGUI::Widget* bottom=overviewSection(root,l.bottom,gpText(office?"locations":"levels"));MyGUI::Widget* info=overviewSection(root,l.info,gpText("information"));int title=overviewLayout.title+2*p;
  MyGUI::ScrollView* scroll=gpScroll(list,p,title,l.list.w-2*p,l.list.h-title-p);MyGUI::ScrollView* details=gpScroll(detail,p,title+4*f+(office?0:3*f),l.details.w-2*p,l.details.h-title-p-4*f-(office?3*f:3*f));MyGUI::TextBox* text=overviewText(details,2,2,details->getWidth()-24,100,f,"");text->setTextAlign(MyGUI::Align::Left|MyGUI::Align::Top);
  MyGUI::ScrollView* infos=gpScroll(info,p,title,l.info.w-2*p,l.info.h-title-p);MyGUI::TextBox* infoText=overviewText(infos,2,2,infos->getWidth()-24,100,f,"");infoText->setTextAlign(MyGUI::Align::Left|MyGUI::Align::Top);gpScrollText(infos,infoText,gpText(office?"office_info":"rep_info"),f);
  gpSymbol(detail,office?0:1,p,title,4*f,registerIvory);MyGUI::TextBox* heroName=overviewText(detail,p+5*f,title,l.details.w-2*p-5*f,2*f,f+2,"");MyGUI::TextBox* heroStatus=overviewText(detail,p+5*f,title+2*f,l.details.w-2*p-5*f,f+5,f,"");
  if(office){goHeroName=heroName;goHeroStatus=heroStatus;goList=scroll;goDetails=details;goDetail=text;goCount=overviewText(list,p,4,l.list.w-2*p,overviewLayout.title+6,overviewLayout.title,"");goCreate=overviewButton(heading,l.heading.w-buttonW-p,4,buttonW,2*f,gpText("create"));goCreate->eventMouseButtonClick+=MyGUI::newDelegate(goCreateClick);goReason=overviewText(heading,l.heading.w-buttonW-p,2*f+6,buttonW,l.heading.h-2*f-8,f,"");goEmpty=overviewText(bottom,p,title,l.bottom.w-2*p,f+4,f,gpText("no_office"));goManage=overviewButton(detail,p,l.details.h-3*f,l.details.w-2*p,2*f,gpText("manage"));goManage->eventMouseButtonClick+=MyGUI::newDelegate(goManageClick);
   goMap=bottom->createWidget<MyGUI::ImageBox>("ImageBox",p,title,l.bottom.w-2*p,l.bottom.h-title-p,MyGUI::Align::Default);goMap->eventMouseWheel+=MyGUI::newDelegate(goWheel);goMap->eventMouseButtonPressed+=MyGUI::newDelegate(goPress);goMap->eventMouseDrag+=MyGUI::newDelegate(goDrag);MyGUI::Widget* legend=overviewPanel(goMap,GuildResponsive::Rect(4,4,10*f,2*f));gpSymbol(legend,2,3,3,2*f-6,registerAmber);overviewText(legend,2*f,0,8*f,2*f,f,gpText("your_office"));MyGUI::Button* plus=overviewButton(bottom,l.bottom.w-p-2*f,l.bottom.h-p-4*f-4,2*f,2*f,"+");MyGUI::Button* minus=overviewButton(bottom,l.bottom.w-p-2*f,l.bottom.h-p-2*f,2*f,2*f,"-");plus->eventMouseButtonClick+=MyGUI::newDelegate(goZoomIn);minus->eventMouseButtonClick+=MyGUI::newDelegate(goZoomOut);goEmpty->setVisible(false);goRefreshMap();
  }else{grHeroName=heroName;grHeroStatus=heroStatus;int headerWidth=scroll->getWidth()-20;
   overviewText(list,p+grLayout.row,4,headerWidth*40/100-grLayout.row,overviewLayout.title+6,f,gpText("faction"));overviewText(list,p+headerWidth*41/100,4,headerWidth*23/100,overviewLayout.title+6,f,gpText("status_column"));overviewText(list,p+headerWidth*65/100,4,headerWidth*15/100,overviewLayout.title+6,f,gpText("value"));
   overviewBar(detail,p,title+4*f,l.details.w-2*p,f,grDetailTrack,grDetailFill);registerSolid(grDetailTrack,grDetailTrack->getWidth()/2,0,1,f,registerIvory);overviewText(detail,p,title+5*f,l.details.w/3,f+2,f,"-100");MyGUI::TextBox* zero=overviewText(detail,l.details.w/2-2*f,title+5*f,4*f,f+2,f,"0");zero->setTextAlign(MyGUI::Align::Center);MyGUI::TextBox* maxValue=overviewText(detail,l.details.w-p-4*f,title+5*f,4*f,f+2,f,"+100");maxValue->setTextAlign(MyGUI::Align::Center);grList=scroll;grDetails=details;grDetail=text;grEmpty=overviewText(list,p,title,l.list.w-2*p,3*f,f,gpText("no_faction"));MyGUI::ScrollView* legend=gpScroll(bottom,p,title,l.bottom.w-2*p,l.bottom.h-title-p);MyGUI::TextBox* legendText=overviewText(legend,2,2,legend->getWidth()-24,100,f,"");legendText->setTextAlign(MyGUI::Align::Left|MyGUI::Align::Top);gpScrollText(legend,legendText,gpText("native_levels"),f);}
  root->setVisible(false);
 }refreshFactionView(true);
}
void go101Update(){if(!go101Guide)return;bool creating=goSelected.empty();go101Guide->setVisible(creating);goReason->setVisible(creating);goDetails->setVisible(!creating);goManage->setVisible(!creating);goHeroName->setVisible(!creating);goHeroStatus->setVisible(!creating);goEmpty->setVisible(goOffices.empty());
 o95Caption(go101Title,creating?o95("CR\303\211ER VOTRE BUREAU","CREATE YOUR OFFICE"):o95("D\303\211TAILS DU BUREAU","OFFICE DETAILS"),22);
 o95Caption(goCount,registerNumber(goOffices.size())+o95(" bureau(x) install\303\251(s) \302\267 "," office(s) registered \302\267 ")+registerNumber(std::max(0,GuildProgression::officeLimit(guildLevel())-(int)goOffices.size()))+o95(" emplacement(s) disponible(s)"," available slot(s)"),18);
 for(size_t i=0;i<goCards.size();++i){GPCard& c=goCards[i];bool present=i<goOffices.size(),available=i<(size_t)GuildProgression::officeLimit(guildLevel());c.name->setTextColour(present||available?o95Ink:MyGUI::Colour(.48f,.48f,.44f));c.city->setTextColour(present||available?o95Ink:MyGUI::Colour(.48f,.48f,.44f));o95Caption(c.name,present?goOffices[i].name:o95("Bureau ","Office ")+registerNumber(i+1),23);o95Caption(c.city,present?mercenarieLocalize(goOffices[i].city):gpText(available?"available":i==0?"level3":"level4"),18);o95Caption(c.note,present?goOffices[i].territory:"",14);o95Caption(c.actionText,present?gpText("manage_short"):available?o95("\303\200 cr\303\251er","Create"):gpText("locked_short"),17);o95Caption(c.status,present?gpText(goOffices[i].active?"active_short":"secondary_short"):"",15);}
 bool capacity=guildLevel()>=3&&(int)goOffices.size()<GuildProgression::officeLimit(guildLevel());if(go102Add)go102Add->setEnabled(capacity);Building* chosen=selectedPlayerBuilding();std::string reason=goCreationReason();goCreate->setVisible(creating);goCreate->setEnabled(capacity&&(!chosen||reason.empty()));o95Caption(goCreate,chosen?o95("Enregistrer le bureau","Register office"):o95("S\303\251lectionner un b\303\242timent","Select a building"),22);goCreate->setTextAlign(MyGUI::Align::Center);o95Caption(goReason,chosen?(reason.empty()?gpText("ready"):reason):gpText(capacity?"select_building":guildLevel()<3?"level3":"limit"),16);
 o95Caption(go101Checks,(chosen?o95("B\303\242timent de votre faction s\303\251lectionn\303\251","Player-owned building selected"):o95("B\303\242timent de votre faction \303\240 s\303\251lectionner","Select a player-owned building"))+"\n"+o95("Chaises Client et Attente \303\240 v\303\251rifier","Client and Waiting chairs to check")+"\n"+o95("Un seul bureau par ville","One office per town"),18);
 o95Caption(go101Next,guildLevel()<3?o95("Niveau 3 \302\267 Premier bureau","Level 3 \302\267 First office"):guildLevel()<4?o95("Niveau 4 \302\267 Jusqu\342\200\231\303\240 3 bureaux","Level 4 \302\267 Up to 3 offices"):o95("Capacit\303\251 d\303\251bloqu\303\251e \302\267 3 bureaux","Unlocked capacity \302\267 3 offices"),20);
 if(!creating){o95Caption(goHeroName,goHeroName->getCaption().asUTF8(),27);o95Caption(goHeroStatus,goHeroStatus->getCaption().asUTF8(),18);goDetail->setFontName("Negotiation74Serif32");goDetail->setFontHeight(op95(22));goDetail->setSize(goDetail->getWidth(),goDetail->getTextSize().height+op95(20));goDetails->setCanvasSize(goDetail->getWidth()+op95(12),std::max(goDetails->getHeight(),goDetail->getHeight()));o95Caption(goManage,gpText("manage"),22);}
}
void buildOffices101(MyGUI::Widget* parent){
 goLayout.font=std::max(12,op95(17));goLayout.pad=op95(12);goLayout.row=op95(64);go101Creating=guildHouseNames.empty();
 guildOfficesPanel=parent->createWidget<MyGUI::Widget>("PanelEmpty",0,0,parent->getWidth(),parent->getHeight(),MyGUI::Align::Default);guildOfficesPanel->setNeedMouseFocus(false);guildOfficesPanel->setInheritsPick(true);
 MyGUI::Widget* list=panel95(guildOfficesPanel,228,114,794,305);ot95(list,20,10,560,32,o95("VOS MAISONS DE GUILDE","YOUR GUILD OFFICES"),24);goCount=ot95(list,20,45,650,26,"",18);go102Add=ob95(list,658,10,116,32,o95("Cr\303\251er +","Create +"));go102Add->eventMouseButtonClick+=MyGUI::newDelegate(go101New);
 goList=gpScroll(list,op95(14),op95(79),op95(766),op95(216));goList->setVisibleVScroll(true);
 MyGUI::Widget* mapPanel=panel95(guildOfficesPanel,228,431,794,355);ot95(mapPanel,20,7,730,31,o95("VOTRE R\303\211SEAU DE BUREAUX","YOUR OFFICE NETWORK"),22);int mapW=op95(766),mapH=op95(278);goMap=mapPanel->createWidget<MyGUI::ImageBox>("ImageBox",op95(14),op95(40),mapW,mapH,MyGUI::Align::Default);goMap->setNeedMouseFocus(true);goMap->setInheritsPick(true);goMap->eventMouseWheel+=MyGUI::newDelegate(goWheel);goMap->eventMouseButtonPressed+=MyGUI::newDelegate(goPress);goMap->eventMouseDrag+=MyGUI::newDelegate(goDrag);goCrop=GuildMapViewport::clamp(0,640,2048,mapW,mapH);goEmpty=ot95(mapPanel,20,325,355,25,gpText("no_office"),16);ot95(mapPanel,405,325,365,25,o95("Molette : zoom \302\267 Glisser : d\303\251placer","Wheel: zoom \302\267 Drag: move"),14);MyGUI::Button* zoom=ob95(mapPanel,735,238,38,38,"+");zoom->eventMouseButtonClick+=MyGUI::newDelegate(goZoomIn);zoom=ob95(mapPanel,735,281,38,38,"-");zoom->eventMouseButtonClick+=MyGUI::newDelegate(goZoomOut);
 MyGUI::Widget* detail=panel95(guildOfficesPanel,1034,114,486,584);go101Title=ot95(detail,20,10,446,34,"",22);registerSolid(detail,op95(20),op95(53),op95(446),1,o95Edge);
 go101Guide=detail->createWidget<MyGUI::Widget>("PanelEmpty",0,op95(60),op95(486),op95(414),MyGUI::Align::Default);go101Guide->setNeedMouseFocus(false);go101Guide->setInheritsPick(true);oi95(go101Guide,3,207,0,72);MyGUI::TextBox* title=ot95(go101Guide,18,77,450,42,o95("Installez votre maison de guilde","Establish your guild office"),25);title->setTextAlign(MyGUI::Align::Center);ot95(go101Guide,20,124,446,32,o95("S\303\251lectionnez un b\303\242timent vous appartenant.","Select a building owned by your faction."),17);
 const char* fr[]={"S\303\251lectionner votre b\303\242timent","V\303\251rifier les \303\251quipements d\342\200\231accueil","Enregistrer le bureau"};const char* en[]={"Select your building","Check reception furniture","Register the office"};for(int i=0;i<3;++i){ot95(go101Guide,22,172+i*42,32,32,registerNumber(i+1),24,true);ot95(go101Guide,64,172+i*42,398,32,o95(fr[i],en[i]),20);}
 registerSolid(go101Guide,op95(20),op95(305),op95(446),1,o95Edge);ot95(go101Guide,20,313,446,28,o95("AVANT DE COMMENCER","BEFORE YOU BEGIN"),18);go101Checks=ot95(go101Guide,20,344,446,70,"",18);
 goHeroName=ot95(detail,20,75,446,55,"",27);goHeroStatus=ot95(detail,20,133,446,32,"",18);goDetails=gpScroll(detail,op95(20),op95(180),op95(446),op95(307));goDetail=ot95(goDetails,2,0,418,100,"",19);goDetail->setTextAlign(MyGUI::Align::Left|MyGUI::Align::Top);
 goReason=ot95(detail,20,482,446,46,"",16);goCreate=ob95(detail,20,532,446,40,"");goCreate->changeWidgetSkin("Board77Gold");goCreate->setTextAlign(MyGUI::Align::Center);goCreate->setTextColour(MyGUI::Colour(.08f,.07f,.04f));goCreate->eventMouseButtonClick+=MyGUI::newDelegate(goCreateClick);goManage=ob95(detail,20,532,446,40,gpText("manage"));goManage->eventMouseButtonClick+=MyGUI::newDelegate(goManageClick);
 MyGUI::Widget* next=panel95(guildOfficesPanel,1034,710,486,76);oi95(next,3,20,14,46);ot95(next,82,7,380,26,o95("CAPACIT\303\211 DES BUREAUX","OFFICE CAPACITY"),17,true);go101Next=ot95(next,82,34,380,32,"",20);goRefreshMap();refreshOfficesView(true);guildOfficesPanel->setVisible(false);
}
