void refreshOverviewChart(const GuildOverview::Finances& data){
 overviewChartEmpty->setVisible(!data.available);long long lo=0,hi=1;for(int s=0;s<3;++s)for(int d=0;d<7;++d){lo=std::min(lo,data.days[s][d]);hi=std::max(hi,data.days[s][d]);}
 int w=overviewChartPlotW-6,h=overviewChart->getHeight()-6;
 for(int s=0;s<3;++s){int yy[7];for(int d=0;d<7;++d){yy[d]=3+h-int(double(data.days[s][d]-lo)*h/double(hi-lo));overviewChartPoints[s][d]->setPosition(1+d*w/6,yy[d]-2);overviewChartPoints[s][d]->setVisible(data.available);}
 for(int j=0;j<192;++j){int day=j/32,part=j%32;int x=3+(day*32+part)*w/192,y=yy[day]+(yy[day+1]-yy[day])*part/32;overviewChartLines[s][j]->setCoord(x,y,std::max(2,w/192+1),2);overviewChartLines[s][j]->setVisible(data.available);}}
}
void refreshRegisterOverview(){
 if(overview95Root&&true){refreshOverview95();return;}
 if(!registerValues[0])return;const GuildProgressView progress=currentGuildProgressView();int level=progress.level;
 float fraction=GuildOverview::xpFraction(progress.xp,progress.next,level);
 std::string xp=registerNumber(progress.xp)+" / "+registerNumber(progress.next)+" XP",levelText=Loc::text("v8.literal.084")+registerNumber(level);
 overviewCaption(guildHeroLevelText,levelText);guildHeroLevelText->setFontHeight(overviewLayout.title);overviewCaption(guildHeroXpText,xp);
 overviewCaption(overviewHeaderLevel,Loc::text("ui.level")+registerNumber(level));std::stringstream headerXp;headerXp<<progress.xp<<" / "<<progress.next<<" XP";overviewCaption(registerQuick[0],headerXp.str());overviewCaption(registerQuick[1],registerNumber(guildHouseNames.size())+" / "+registerNumber(GuildProgression::officeLimit(level)));overviewCaption(registerQuick[2],reputationRank(escortReputation)+" ("+registerNumber((long long)escortReputation)+")");
 int members=ou&&ou->player?(int)ou->player->playerCharacters.size():0;
 int funds=ou&&ou->player&&ou->player->participant&&ou->player->participant->factionOwnerships?ou->player->participant->factionOwnerships->getMoney():0;
 overviewCaption(registerQuick[3],registerNumber(funds)+" Cats");overviewCaption(overviewStats[0],registerNumber(members));overviewCaption(overviewStats[1],registerNumber(guildHouseNames.size()));overviewCaption(overviewStats[2],registerNumber(successfulContracts));overviewCaption(overviewStats[3],registerNumber(funds)+" Cats");
 overviewFill(overviewHeroTrack,overviewHeroFill,fraction);overviewFill(overviewHeaderTrack,overviewHeaderFill,fraction);
 overviewCaption(registerTimelineLevel,levelText);overviewCaption(registerTimelineDetail,xp);overviewCaption(registerTimelineNext,level>=10?Loc::text("v8.literal.085"):Loc::text("v8.literal.084")+registerNumber(level+1));
 overviewTimelineFill(fraction);
 int active=overviewEscortCount(false),expeditions=overviewEscortCount(true);
 for(size_t i=0;i<delegatedMissions.size();++i)if(delegatedMissions[i].timing.active){++active;if(delegatedMissions[i].timing.activityType==DelegatedMissionTiming::ActivityScientificExpedition)++expeditions;}
 for(size_t i=0;i<mailContracts.size();++i)if(mailContracts[i].status==MailContracts::MailActive)++active;
 active+=overviewBountyCount();
 overviewCaption(registerValues[0],registerNumber(active));overviewCaption(registerValues[1],registerNumber(expeditions));overviewCaption(registerValues[2],registerNumber(successfulContracts));for(int i=0;i<3;++i)registerValues[i]->setFontHeight(overviewFont+4);
 GuildOverview::Finances money=GuildOverview::finances(fiscalLedger.cash,currentGameHours);overviewCaption(overviewMoney[0],registerNumber(money.income));overviewCaption(overviewMoney[1],registerNumber(money.expense));overviewCaption(overviewMoney[2],Loc::text("v8.literal.086"));overviewCaption(overviewMoney[3],registerNumber(money.income-money.expense));overviewCaption(overviewMoney[4],registerNumber(funds)+" Cats");refreshOverviewChart(money);
 overviewCaption(overviewInfo[0],registerNumber(localReputations.size()));overviewCaption(overviewInfo[1],Loc::text("guild.pages.not_tracked"));overviewCaption(overviewInfo[2],level>=10?Loc::text("v8.literal.085"):Loc::text("v8.literal.084")+registerNumber(level+1));overviewCaption(overviewInfo[3],level>=10?Loc::text("v8.literal.087"):registerNumber(progress.next-progress.xp)+" XP");overviewCaption(overviewInfo[4],registerNumber(guildHouseNames.size()));
 int shown=0;for(size_t i=0;i<contractHistory.size()&&shown<overviewRecentCapacity;++i){if(contractHistory[i].compare(0,12,"@investment:")==0)continue;GuildHistory::Summary row=GuildHistory::parse(contractHistory[i]);GuildHistory::Snapshot snapshot;bool structured=GuildHistory::decode(contractHistory[i],snapshot);overviewRecentCaption(overviewRecent[shown],structured?std::string(Loc::text(("contracts.type."+snapshot.type).c_str()))+" > "+mercenarieLocalize(snapshot.destination.empty()?snapshot.target:snapshot.destination):registerActivity(row.route));overviewCaption(overviewRecentResults[shown],structured&&snapshot.status==4?Loc::text("contracts.ui.cancelled"):row.status==1?Loc::text("contracts.ui.completed_single"):row.status==2?Loc::text("contracts.ui.failed_single"):"");overviewCaption(overviewRecentBonus[shown],row.bonus==0?Loc::text("contracts.ui.bonus_no"):row.bonus==1?Loc::text("contracts.ui.bonus_yes"):row.bonus==2?Loc::text("contracts.ui.bonus_requested"):registerActivity(row.result));overviewRecentBonus[shown]->setTextColour(row.bonus==0||(row.bonus<0&&row.reward==0)?MyGUI::Colour(1,.28f,.20f):row.bonus==1||row.reward>0?registerGreen:registerIvory);overviewRecent[shown]->setVisible(true);overviewRecentResults[shown]->setVisible(true);overviewRecentBonus[shown]->setVisible(true);overviewRecentIcons[shown]->setVisible(true);++shown;}for(int i=shown;i<3;++i){overviewRecent[i]->setVisible(false);overviewRecentResults[i]->setVisible(false);overviewRecentBonus[i]->setVisible(false);overviewRecentIcons[i]->setVisible(false);}overviewEmpty->setVisible(shown==0);
 refreshRegisterInfluenceMap();
 for(int i=0;i<10;++i){int n=i+1;MyGUI::Colour color=n<level?registerGreen:n==level?registerAmber:n==level+1?registerIvory:MyGUI::Colour(.50f,.52f,.50f);std::string state=n<level?Loc::text("v8.literal.088"):n==level?Loc::text("v8.literal.089"):n==level+1?Loc::text("v8.literal.090"):Loc::text("v8.literal.091");overviewCaption(registerLevelStates[i],Loc::text("v8.literal.092")+registerNumber(n)+"\n"+state);registerLevelStates[i]->setTextColour(color);registerLevelIcons[i]->setColour(color);registerLevelButtons[i]->setStateSelected(n==level);for(int e=0;e<4;++e){registerLevelAccents[i][e]->setColour(n==level?registerAmber:n<level?MyGUI::Colour(.28f,.40f,.20f):MyGUI::Colour(.25f,.28f,.27f));}}
 if(!registerCarouselInitialized)registerCenterLevelCarousel(level);registerCarouselStart=GuildOverview::move(registerCarouselStart,0,std::max(1,level));registerLayoutLevelCarousel();
 int next=std::min(10,level+1);overviewCaption(overviewNextTitle,level>=10?Loc::text("v8.literal.093"):Loc::text("v8.literal.094")+registerNumber(next));overviewCaption(overviewNextLevel,level>=10?Loc::text("v8.literal.095"):Loc::text("ui.level")+registerNumber(next));registerSetProgressIcon(registerNextArt,next);
 std::vector<GuildLevelUI::Unlock> unlocks=GuildLevelUI::unlocks(next);std::stringstream out;if(unlocks.empty())out<<Loc::text("v8.literal.096");else for(size_t i=0;i<unlocks.size()&&i<3;++i){if(i)out<<"\n";out<<(gMercenarieEnglish?unlocks[i].en:unlocks[i].fr);}if(unlocks.size()>3)out<<"\n"<<Loc::text("v8.literal.097");overviewCaption(registerNextTier,out.str());
}
