#pragma once
struct MercenarieTranslation { const char* fr; const char* en; };
static const MercenarieTranslation kMercenarieTranslations[] = {
    {"CONTINUER","CONTINUE"},
    {"REFUSER LE CONTRAT","DECLINE THE CONTRACT"},
    {"Etat : ","Status: "},
    {"Bonjour. Nous sommes ","Hello. We are "},
    {"Contrats actifs","Active contracts"},
    {"Montant actuellement\ndu","Amount currently\ndue"},
    {"REGLES FISCALES","TAX RULES"},
    {"REVENUS BRUTS","GROSS INCOME"},
    {"TAXES PAYEES","TAXES PAID"},
    {"DETTE TOTALE","TOTAL DEBT"},
    {"Montant total","Total amount"},
    {"deja paye","already paid"},
    {"Montant actuellement","Amount currently"},
    {"CITES UNIES","UNITED CITIES"},
    {"STATUT","STATUS"},
    {"TAUX DE TAXE","TAX RATE"},
    {"DETTE ACTUELLE","CURRENT DEBT"},
    {"ETAT","STATE"},
    {"HISTORIQUE COMPTABLE","ACCOUNTING HISTORY"},
    {"Aucun enregistrement comptable pour le moment.","No accounting entries yet."},
    {"REPUTATIONS LOCALES","LOCAL REPUTATIONS"},
    {"REPUTATION GLOBALE","GLOBAL REPUTATION"},
    {"TERRITOIRES CONNUS","KNOWN TERRITORIES"},
    {"CONTRATS REUSSIS","COMPLETED CONTRACTS"},
    {"VILLES","CITIES"},
    {"DETAIL DU TERRITOIRE","TERRITORY DETAILS"},
    {"Aucun lieu selectionne.","No location selected."},
    {"Selectionnez un lieu dans la liste pour afficher ses informations.","Select a location in the list to view its details."},
    {"Bureaux enregistres","Registered offices"},
    {"BUREAUX DE THE MERCENARIE","THE MERCENARIE OFFICES"},
    {"MAISON SELECTIONNEE","SELECTED GUILD HOUSE"},
    {"CREER UN BUREAU","CREATE AN OFFICE"},
    {"CONTRAT ACTIF","ACTIVE CONTRACT"},
    {"STATISTIQUES","STATISTICS"},
    {"ECHECS","FAILURES"},
    {"TAUX DE REUSSITE","SUCCESS RATE"},
    {"CATS GAGNES","CATS EARNED"},
    {"PROCHAIN DEBLOCAGE","NEXT UNLOCK"},
    {"ESCORTE DE CARAVANE","CARAVAN ESCORT"},
    {"CARAVANE","CARAVAN"},
    {"COMMUN","COMMON"},
    {"REGLES FISCALES\n\nCITES UNIES\nTaux normal : 20 % | Allie : 5 % | Rebelle : 0 %\nMissions dont le depart ou l'arrivee appartient aux Cites Unies lors du paiement. Une seule taxe par mission.\nCollecte tous les 7 jours.\n\nGUILDE DES MERCENAIRES\nTaux normal : 10 % | Allie : 5 % | Rebelle : 0 %\nToutes les missions reussies et payees.\n\nLes primes finales et pourboires ne sont jamais taxes.","TAX RULES\n\nUNITED CITIES\nStandard rate: 20% | Allie: 5% | Rebel: 0%\nMissions whose departure or arrival belongs to the United Cities upon payment. Only one fee per mission.\nCollection every 7 days.\n\nMERCENARY GUILD\nStandard rate: 10% | Allie: 5% | Rebel: 0%\nAll missions completed and paid for.\n\nFinal bonuses and tips are never taxed."},
    {"PNJ : Voici les conditions du contrat.\n\nTYPE : %s\nTRAJET : %s  >  %s%s\nDISTANCE : %.1f km\nDANGER : %.1f / 3\nREMUNERATION : %d Cats\n\nVotre niveau de Guilde ne permet pas encore de negocier.\nVous pouvez uniquement accepter ou refuser ces conditions.","NPC: These are the terms of the contract.\n\nTYPE: %s\nROUTE: %s > %s%s\nDISTANCE: %.1f km\nDANGER: %.1f / 3\nREMUNERATION: %d Cats\n\nYour Guild level does not yet allow you to negotiate.\nYou can only accept or reject these terms."},
    {"REGLES FISCALES\n\nCITES UNIES : 20 % (5 % si allie) sur les missions liees a leur territoire.\nGUILDE DES MERCENAIRES : 10 % (5 % si allie) sur les missions reussies et payees.\n\nLes primes finales et pourboires ne sont jamais taxes.","TAX RULES\n\nUNITED CITIES: 20% (5% if allied) on missions connected to their territory.\nMERCENARY GUILD: 10% (5% if allied) on completed, paid missions.\n\nFinal bonuses and tips are never taxed."},
    {"%s  |  %s\n\nREPUTATION : %.1f\nRANG : %s\n\nBONUS DE REMUNERATION : %+d%%\nCHANCE DE CONTRAT PRESTIGIEUX : %d%%\nCONFIANCE EN NEGOCIATION : %s\n\nEffectuez des missions reussies ici pour ameliorer ces avantages.","%s |  %s\n\nREPUTATION: %.1f\nRANK: %s\n\nBONUS PAY: %+d%%\nCHANCE OF PRESTIGIOUS CONTRACT: %d%%\nNEGOTIATION CONFIDENCE: %s\n\nComplete successful missions here to upgrade these perks."},
    {" tient les comptes de vos contrats depuis leur paiement. Personne ne pouvait venir avant l'ouverture de votre Maison de Guilde. Les anciennes taxes sont toujours dues.\n\nLe taux normal est de ","keeps the accounts of your contracts since their payment. No one could come before your Guild House opened. Old taxes are still due.\n\nThe normal rate is"},
    {"%s  |  %s\n\nREPUTATION : %.1f\nRANG : %s\n\nBONUS DE REMUNERATION : %+d%%\nCHANCE DE CONTRAT PRESTIGIEUX : %d%%\nCONFIANCE EN NEGOCIATION : %s\n\nCe lieu possede sa propre memoire de vos contrats.","%s |  %s\n\nREPUTATION: %.1f\nRANK: %s\n\nBONUS PAY: %+d%%\nCHANCE OF PRESTIGIOUS CONTRACT: %d%%\nNEGOTIATION CONFIDENCE: %s\n\nThis place has its own memory of your contracts."},
    {"REACTION PREVISIBLE : %s\nConsequences : %d Cats | Reputation estimee : %+.1f | XP de Guilde inchangee.\nZone verte : raisonnable | orange : risquee | rouge : demande excessive.","EXPECTED REACTION: %s\nConsequences: %d Cats | Estimated reputation: %+.1f | Guild XP unchanged.\nGreen: reasonable | orange: risky | red: excessive demand."},
    {"Selectionnez un batiment vous appartenant\ndans le monde, puis utilisez l'action :\n\nDEFINIR BATIMENT DE GUILDE\n\nLe bureau pourra accueillir les clients\net gerer vos contrats.","Select a building you own\nin the world, then use:\n\nSET GUILD BUILDING\n\nThe office can receive clients\nand manage your contracts."},
    {"Chaise avec dossier reservee au client principal venu proposer un contrat. Une Chaise Client et une Chaise d'Attente sont necessaires pour identifier une Maison de Guilde.","Chair with backrest reserved for the main client who comes to propose a contract. A Client Chair and a Waiting Chair are required to identify a Guild House."},
    {"A backed chair reserved for the main client offering a contract. One Client Chair and one Waiting Chair are required to identify a Guild House.","A backed chair reserved for the main client offering a contract. One Client Chair and one Waiting Chair are required to identify a Guild House."},
    {"AUCUNE REPUTATION ENREGISTREE\n\nTerminez des contrats dans differents lieux pour gagner en reputation et debloquer de nouvelles opportunites.","NO REPUTATION RECORDED\n\nComplete contracts in different locations to earn reputation and unlock new opportunities."},
    {"AUCUNE REPUTATION ENREGISTREE\n\nTerminez des contrats dans differents lieux\npour gagner en reputation et debloquer\nde nouvelles opportunites.","NO REPUTATION RECORDED\n\nComplete contracts in different locations\nto earn reputation and unlock\nnew opportunities."},
    {"Chaise avec dossier reservee aux visiteurs et accompagnateurs. Chaque chaise augmente la capacite d'accueil de la Maison de Guilde.","Chair with backrest reserved for visitors and chaperones. Each chair increases the accommodation capacity of the Guild House."},
    {"Aucune Maison de Guilde enregistree.\n\nSelectionnez un batiment appartenant au joueur puis utilisez :\nDEFINIR BATIMENT DE GUILDE","No registered Guild House.\n\nSelect a building belonging to the player then use:\nDEFINE GUILD BUILDING"},
    {"REBELLION FISCALE : les trois equipes de recouvrement ont ete repoussees. Cette organisation cesse de taxer votre compagnie.","TAX REBELLION: the three collection teams were rejected. This organization stops taxing your company."},
    {"AUCUNE REPUTATION DANS CETTE CATEGORIE\n\nTerminez des contrats dans de nouveaux lieux pour enrichir le registre de la Guilde.","NO REPUTATION IN THIS CATEGORY\n\nComplete contracts in new locations to enrich the Guild ledger."},
    {"Bonjour. Nous sommes la compagnie engagee par le barman. Avant le depart, j'aimerais discuter de la remuneration avec vous.","Good morning. We are the company hired by the bartender. Before departure, I would like to discuss remuneration with you."},
    {"Le client du contrat n'existe plus apres le chargement. Le suivi a ete nettoye sans acceder a une reference invalide.","The contract client no longer exists after loading. The trace was cleaned up without accessing an invalid reference."},
    {"Aucun contrat termine pour le moment.\n\nAccomplissez des missions pour developper\nvotre reputation et gagner des Cats.","No completed contracts yet.\n\nComplete missions to build your\nreputation and earn Cats."},
    {"LEGENDE   [VERT] Depart   [ROUGE] Arrivee   [OR] Prestigieux\nSurvolez les contrats pour comparer distance et danger.","LEGEND [GREEN] Departure [RED] Arrival [GOLD] Prestigious\nHover over the contracts to compare distance and danger."},
    {"MAISON DE GUILDE OPERATIONNELLE : la Chaise Client et la Chaise d'Attente ont ete detectees dans le batiment defini.","OPERATIONAL GUILD HOUSE: The Client Chair and Waiting Chair have been detected in the defined building."},
    {"Une petite compagnie dans un monde sans loi. Gagnez en reputation,\nacceptez des contrats et developpez votre reseau.","A small company in a lawless world. Build your reputation,\naccept contracts and expand your network."},
    {"Negociation verrouillee jusqu'au niveau 2. Vous pouvez accepter les conditions initiales ou refuser le contrat.","Negotiation locked up to level 2. You can accept the initial conditions or refuse the contract."},
    {"Accueil de la Guilde desactive : il faut au moins 1 Chaise Client et 1 Chaise d'Attente dans le meme batiment.","Guild reception disabled: at least 1 Client Chair and 1 Waiting Chair are required in the same building."},
    {"Comment voulez-vous appeler cette Maison de Guilde ?\nCe nom permettra d'identifier les alertes de cette ville.","What do you want to call this Guild House?\nThis name will identify the alerts for this city."},
    {"CONTRAT TERMINE : +%d Cats%s | Reputation locale mise a jour | XP de Guilde : +%d | Progression : %d / %d XP.","CONTRACT COMPLETED: +%d Cats%s | Local reputation updated | Guild XP: +%d | Progress: %d / %d XP."},
    {"Batiment defini comme Maison de Guilde. Installez une Chaise Client et une Chaise d'Attente dans ce batiment.","Building defined as Guild House. Install a Customer Chair and a Waiting Chair in this building."},
    {"[i] Recherches terminees a l'exterieur : observations historiques consignees, aucune decouverte interieure.\n","[i] Exterior research completed: historical observations recorded, no interior discoveries."},
    {"L'equipe de recouvrement revient comme promis. Payez maintenant ou elle mettra votre equipe hors de combat.","The collection team returns as promised. Pay now or she will put your team out of action."},
    {"Le barman nous a parle de votre caravane et nous sommes ici pour assurer sa protection pendant le trajet. ","The bartender told us about your caravan and we are here to ensure its protection during the journey."},
    {"Test impossible : definissez le batiment de Guilde et placez-y une Chaise Client et une Chaise d'Attente.","Impossible test: define the Guild building and place a Client Chair and a Waiting Chair there."},
    {"Le barman nous a parle de votre expedition scientifique et nous sommes ici pour proteger vos recherches. ","The bartender told us about your scientific expedition and we are here to protect your research."},
    {"Pitoyable. Nous reviendrons dans sept jours. Si vous ne payez toujours pas, nous vous ecraserons encore.","Pitiful. We will return in seven days. If you still don't pay, we'll crush you again."},
    {"Aucun bureau selectionne.\n\nChoisissez une Maison de Guilde\ndans la liste pour afficher\nses informations.","No office selected.\n\nChoose a Guild House\nfrom the list to view\nits details."},
    {"Fonds insuffisants. Vous possedez %d Cats, mais le collecteur exige le paiement integral de %lld Cats.","Insufficient funds. You own %d Cats, but the Collector demands full payment of %lld Cats."},
    {"Debloque les sieges necessaires pour identifier et exploiter une Maison de Guilde de The Mercenarie.","Unlocks the seats needed to identify and operate a Guild House in The Mercenarie."},
    {"%s   |   CLIENT : %s\n%s  >  %s%s     |     %.1f km     |     DANGER %.1f/3     |     OFFRE %d Cats","%s |   CUSTOMER: %s\n%s > %s%s |     %.1f km |     DANGER %.1f/3 |     OFFER %d Cats"},
    {"OUTILS DE DEVELOPPEMENT ET DE TEST\nLeur utilisation peut modifier la progression de votre partie.","DEVELOPMENT AND TESTING TOOLS\nTheir use can change the progress of your game."},
    {"On raconte qu'une route voisine est devenue dangereuse. Cela pourrait interesser vos mercenaires.","It is said that a nearby road has become dangerous. This might interest your mercenaries."},
    {" Nouveau : les clients peuvent maintenant venir directement proposer leurs contrats a la Guilde.","New: customers can now come directly to offer their contracts to the Guild."},
    {"Je represente l'administration fiscale. Je suis ici pour percevoir la part due sur vos contrats.","I represent the tax administration. I am here to collect the share owed on your contracts."},
    {"Accueil de la Guilde actif : Chaise Client et Chaise d'Attente detectees dans le meme batiment.","Guild reception active: a Client Chair and a Waiting Chair were detected in the same building."},
    {"L'equipe scientifique vous attend devant le batiment. Parlez au chef avant l'expedition vers ","The scientific team is waiting for you in front of the building. Talk to the leader before the expedition to "},
    {"Regardez ces marques sur les ruines. Quelqu'un a voulu effacer une partie de cette histoire.","Look at these marks on the ruins. Someone wanted to erase part of this history."},
    {"- Aucun nouvel avantage pour le moment\n- De nouveaux avantages seront ajoutes ulterieurement","- No new benefits at the moment\n- New benefits will be added later"},
    {"Aucun contrat actif.\nConsultez un barman ou une Maison de Guilde pour obtenir une mission.","No active contract.\nVisit a bartender or a Guild House to obtain a mission."},
    {"Ces debris ne sont pas disposes au hasard. Une bataille ou un effondrement a eu lieu ici.","These debris are not arranged randomly. A battle or collapse took place here."},
    {"Contrat annule : un membre de la faction Joueur a porte le voyageur plus de 20 secondes.","Contract canceled: a member of the Player faction carried the traveler for more than 20 seconds."},
    {"- Creation d'une premiere Maison de Guilde\n- Recherche des Armures de Guilde disponible","- Creation of a first Guild House\n- Search for available Guild Armor"},
    {"Siege de bureau reserve au collecteur fiscal venu rencontrer le dirigeant de la Guilde.","Office seat reserved for the tax collector who came to meet the leader of the Guild."},
    {"La caravane vous attend devant le batiment. Parlez au maitre avant l'aller-retour vers ","The caravan awaits you in front of the building. Talk to the master before the round trip to"},
    {"Fonction verrouillee : atteignez le niveau 3 de Guilde pour creer une Maison de Guilde.","Locked Feature: Reach Guild Level 3 to create a Guild House."},
    {"Le collecteur reste assis dans la Maison de Guilde. Parlez-lui lorsque vous serez pret.","The collector remains seated at the Guild House. Speak to them when you are ready."},
    {"Nous sommes revenus pour la collecte. Voici ce que votre compagnie doit actuellement.","We came back for the collection. Here's what your company currently owes."},
    {"Les marchandises sont livrees. Nous repartons maintenant vers notre ville de depart.","The goods are delivered. We are now heading back to our departure city."},
    {"Cette structure a resiste pendant des siecles. Sa fonction devait etre importante.","This structure has stood for centuries. Its function must have been important."},
    {"Cette Maison de Guilde inspire davantage confiance que les tavernes de la region.","This Guild House inspires more confidence than the taverns in the region."},
    {"Inactif : installez 1 Chaise Client et 1 Chaise d'Attente dans le meme batiment.\n","Inactive: install 1 Customer Chair and 1 Waiting Chair in the same building."},
    {"On m'a recommande vos services. J'espere ne pas avoir fait le voyage pour rien.","I was recommended your services. I hope I didn't make the trip for nothing."},
    {"- Deux Maisons de Guilde supplementaires\n- Maximum porte a 3 Maisons de Guilde","- Two additional Guild Houses\n- Maximum door to 3 Guild Houses"},
    {"Nouvel objectif : raccompagner les scientifiques jusqu'a leur ville d'origine.","New objective: accompany the scientists back to their city of origin."},
    {" primes\nLes primes modifient l'argent et la reputation, jamais l'XP de Guilde.","bonuses\nBounties modify money and reputation, never Guild XP."},
    {"Contrat refuse : le client a interrompu la negociation apres deux insistances.","Contract refused: the client interrupted the negotiation after two insistences."},
    {"Vous etes la compagnie envoyee par le barman pour proteger notre expedition ?","Are you the company sent by the bartender to protect our expedition?"},
    {"RELATIONS DE LA GUILDE\n\nLes relations sont propres a chaque lieu et region.\n\n","GUILD RELATIONS\n\nRelationships are specific to each place and region."},
    {"CARTE DU MONDE  |  Molette : zoom  |  Clic gauche : deplacer\n\nTRAJET  [VERT] ","WORLD MAP |  Wheel: zoom |  Left click: move\n\nJOURNEY [GREEN]"},
    {"Dette fiscale integralement payee. La procedure de recouvrement est terminee.","Tax debt fully paid. The recovery procedure is completed."},
    {"La serrure a cede. Ces salles pourraient contenir des informations capitales.","The lock gave way. These rooms could contain vital information."},
    {"Ces fondations de ce site sont bien plus anciennes que les royaumes actuels.","These foundations of this site are much older than the current kingdoms."},
    {"Le chef scientifique tente de crocheter l'entree des ruines avec ses outils.","The chief scientist tries to pick the entrance to the ruins with his tools."},
    {"Le voyageur vous attend devant le batiment. Parlez-lui avant le depart vers ","The traveler is waiting for you in front of the building. Talk to him before leaving for"},
    {"Impossible d'enregistrer ce bureau : la ville n'est pas reconnue par Kenshi.","This office cannot be registered: Kenshi does not recognize its city."},
    {"Vous etes la compagnie envoyee par le barman pour proteger notre caravane ?","Are you the company sent by the bartender to protect our caravan?"},
    {" soldats. Payez integralement maintenant ou refusez et affrontez l'equipe.","soldiers. Pay in full now or decline and face the team."},
    {"Contrat annule : le voyageur est reste inconscient plus de 1 000 secondes.","Contract canceled: the traveler remains unconscious for more than 1,000 seconds."},
    {"Deplacez le curseur de -20 % a +25 %. Le budget reel du client est cache.","Move the slider from -20% to +25%. The client's actual budget is hidden."},
    {"Votre salle d'attente est modeste, mais votre reputation m'a conduit ici.","Your waiting room is modest, but your reputation led me here."},
    {"Accord conclu : avance de %d%% (%d Cats). Le solde sera paye a l'arrivee.","Agreement reached: advance of %d%% (%d Cats). The balance will be paid on arrival."},
    {" %, reduit a 5 % pour un allie. Un collecteur reviendra tous les 7 jours.","%, reduced to 5% for an ally. A collector will return every 7 days."},
    {"Deplacez le curseur de -20 % a +50 %. Le budget reel du client est cache.","Move the slider from -20% to +50%. The client's actual budget is hidden."},
    {"Test impossible : toutes les places de la Maison de Guilde sont occupees.","Impossible test: all the places in the Guild House are occupied."},
    {"Limite atteinte : votre niveau de Guilde autorise %d Maison(s) de Guilde.","Limit reached: your Guild level allows %d Guild House(s)."},
    {"Cette Maison de Guilde est maintenant le bureau actif et le siege fiscal.","This Guild House is now the active office and tax headquarters."},
    {"Aucune Maison : placez les deux chaises dans le meme batiment du joueur.","No House: Place both chairs in the same player building."},
    {"Nous avons obtenu suffisamment d'informations. Il est temps de rentrer.","We have obtained enough information. It's time to go home."},
    {". Installez une Chaise Client et une Chaise d'Attente dans ce batiment.",". Install a Customer Chair and a Waiting Chair in this building."},
    {"Test impossible : parlez d'abord a un barman ou faites venir un client.","Impossible test: first talk to a bartender or bring in a customer."},
    {"Vous etes la compagnie envoyee par le barman pour assurer mon escorte ?","Are you the company sent by the bartender to provide my escort?"},
    {"NEGOCIATION  %+.0f%%     |     AVANCE  %d Cats     |     SOLDE  %d Cats","NEGOTIATION %+.0f%% |     ADVANCE %d Cats |     SALE %d Cats"},
    {"Votre derniere escorte s'est bien terminee. Je reviens donc vous voir.","Your last escort ended well. So I'll come back to see you."},
    {"ALLURE ADAPTEE : le client ralentit pour un membre eloigne ou blesse.","ADAPTIVE PACE: the client slows down when an important group member is too far away or injured."},
    {"Etape aller terminee : protegez la caravane pendant le trajet retour.","Outward leg completed: protect the caravan during the return journey."},
    {"\n\nSPECIALISATION\nProtecteurs fiables\nConfiance des clients amelioree","SPECIALIZATION\nReliable protectors\nImproved customer confidence"},
    {"Refus confirme. Une equipe de recouvrement arrivera dans deux jours.","Refusal confirmed. A recovery team will arrive in two days."},
    {"Entree reussie : l'expedition poursuit ses recherches a l'interieur.","Entry successful: the expedition continues its search inside."},
    {"Notez tout. Ce site pourrait changer notre lecture du Second Empire.","Write everything down. This site could change our reading of the Second Empire."},
    {"PRIMES  +%d Cats     |     AVANCE  %d Cats     |     SOLDE  %d Cats","PREMIUMS +%d Cats |     ADVANCE %d Cats |     SALE %d Cats"},
    {"Aucun contrat actif.\nConsultez un barman pour obtenir une mission.\n","No active contract.\nConsult a bartender to get an assignment."},
    {"Choisissez une reponse au collecteur avant de fermer cette fenetre.","Choose a response to the collector before closing this window."},
    {" nouvelle(s). Les decouvertes sont enregistrees avec la sauvegarde.","news). Discoveries are recorded with the backup."},
    {"Aucun contrat actif.\nConsultez un barman\npour obtenir une mission.\n","No active contract.\nSpeak to a bartender\nto obtain a mission.\n"},
    {"Avant le depart, j'aimerais discuter de la remuneration avec vous.","Before we leave, I would like to discuss payment with you."},
    {" : observation exterieure avant une eventuelle tentative d'entree.",": external observation before a possible entry attempt."},
    {"AVIS FISCAL : un collecteur de %s arrivera dans environ un jour.","TAX NOTICE: A %s collector will arrive in about a day."},
    {"\n\nVous confirmez votre refus ? Une procedure armee sera engagee.","Do you confirm your refusal? An armed procedure will be initiated."},
    {"Impossible. Le mecanisme est trop endommage; poursuivons dehors.","Impossible. The mechanism is too damaged; let's continue outside."},
    {"Quel type d'equipement de la Guilde recherchez-vous, mon frere ?","What kind of Guild equipment are you looking for, brother?"},
    {"Crochetage echoue : les recherches continuent autour des ruines.","Lockpick fails: search continues around the ruins."},
    {"Test impossible : un contrat est deja en attente de validation.","Test impossible: a contract is already awaiting validation."},
    {"NIVEAU MAXIMUM — GUILDE LEGENDAIRE\n10000 / 10000 XP\nPRESTIGE : ","MAXIMUM LEVEL — LEGENDARY GUILD\n10000 / 10000 XP\nPRESTIGE:"},
    {"Votre compagnie possede desormais un etablissement officiel.\n\n","Your company now has an official establishment."},
    {"Negociation suspendue. Reparlez au voyageur pour la reprendre.","Negotiation suspended. Speak to the traveler again to take it back."},
    {"Le voyageur est sorti. Le trajet vers la destination commence.","The traveler has gone out. The journey to the destination begins."},
    {"J'entends une bete agressive dans les environs. Preparez-vous.","I hear an aggressive beast nearby. Prepare yourself."},
    {"Contrat annule : un membre essentiel de la caravane est mort.","Contract canceled: an essential member of the caravan is dead."},
    {"THE MERCENARY   |   REGISTRE DE LA GUILDE   |   J POUR FERMER","THE MERCENARY |   GUILD REGISTRY |   J TO CLOSE"},
    {"Les materiaux de cette ruine revelent une technologie perdue.","The materials from this ruin reveal lost technology."},
    {"Premiere Maison de Guilde et recherche des Armures de Guilde","First Guild House and search for Guild Armor"},
    {"Debloque l'equipement prestigieux du dirigeant de la Guilde.","Unlocks prestigious Guild Leader gear."},
    {"Gerez vos bureaux de Guilde et leurs services dans le monde.","Manage your Guild offices and their services across the world."},
    {"Guild Escort Contracts 0.3 local reputation and negotiation","Guild Escort Contracts 0.3 local reputation and negotiation"},
    {"[X] Protection rapprochee pendant plus de 70% du trajet : +","[X] Close protection for more than 70% of the journey: +"},
    {"Une Maison de Guilde est deja enregistree dans cette ville.","A Guild House is already registered in this city."},
    {"CONTRAT ACCEPTE — cette offre est liee a la mission active.","CONTRACT ACCEPTED — this offer is linked to the active mission."},
    {"\n\nINDISPONIBLE : niveau ou reputation locale insuffisante.","UNAVAILABLE: insufficient local level or reputation."},
    {"Masque noir distinctif porte par les membres de la Guilde.","Distinctive black mask worn by members of the Guild."},
    {" NIVEAU MAXIMUM — l'XP supplementaire devient du prestige.","MAXIMUM LEVEL — Extra XP becomes Prestige."},
    {"/3\n\nLe delai est termine. Le collecteur est accompagne de ","/3\n\nThe deadline is over. The collector is accompanied by"},
    {"L'escorte commence. Le voyageur rejoint d'abord la sortie.","The escort begins. The traveler first reaches the exit."},
    {"Contrat annule : un scientifique de l'expedition est mort.","Contract canceled: a scientist from the expedition is dead."},
    {"Bottes prestigieuses reservees au dirigeant de la Guilde.","Prestigious boots reserved for the leader of the Guild."},
    {"Aucune dette n'est actuellement due a cette organisation.","No debt is currently owed to this organization."},
    {"Une patrouille locale controle la route. Restons calmes.","A local patrol controls the road. Let's stay calm."},
    {"Non. Nous vous avons deja accorde suffisamment de temps.","No. We have already given you enough time."},
    {"Debloque l'equipement reserve aux sergents de la Guilde.","Unlocks equipment reserved for Guild sergeants."},
    {"Contrat de test nettoye sans consequence supplementaire.","Test contract cleaned without additional consequences."},
    {"J'ai deja fait deux efforts. La discussion est terminee.","I have already made two efforts. The discussion is over."},
    {"Je joins un objet utile au paiement. Vous l'avez merite.","I enclose a useful item with payment. You deserved it."},
    {"Un ancien client satisfait m'a recommande vos services.","A former satisfied customer recommended your services to me."},
    {"Nous avons fait la moitie du chemin. Restons vigilants.","We are halfway there. Let's remain vigilant."},
    {"Un contrat est deja present. Nettoyez-le avant ce test.","A contract is already present. Clean it before this test."},
    {"Ce batiment est deja enregistre comme Maison de Guilde.","This building is already registered as a Guild House."},
    {"Plastron prestigieux reserve au dirigeant de la Guilde.","Prestigious breastplate reserved for the leader of the Guild."},
    {")<<FiscalLedger::rate(o,relation)<<mercenarieLocalize(",")<<FiscalLedger::rate(o,relation)<<mercenarieLocalize("},
    {"J'ai assez attendu. Je proposerai ce contrat ailleurs.","I've waited long enough. I will offer this contract elsewhere."},
    {"Le barman nous a envoyes pour assurer votre escorte. ","The bartender sent us to secure your escort."},
    {"<<static_cast<int>(boardOffers[i].distance/1000.0f)<<","<<static_cast<int>(boardOffers[i].distance/1000.0f)<<"},
    {"Le contrat ne peut pas demarrer : donnees manquantes.","The contract cannot start: missing data."},
    {"[X] Cargaison intacte et tous les animaux revenus : +","[X] Cargo intact and all animals returned: +"},
    {"Veux-tu acheter des armures de la Guilde, mon frere ?","Do you want to buy some armor from the Guild, brother?"},
    {"C'est tout ? J'ai connu des chevres plus dangereuses.","Is that all? I have known more dangerous goats."},
    {"Casque prestigieux reserve au dirigeant de la Guilde.","Prestigious helmet reserved for the leader of the Guild."},
    {"Guild Escort: visible contract reply added to barman","Guild Escort: visible contract reply added to bartender"},
    {"Aucune relation connue. Terminez un premier contrat.","No known relationship. Complete a first contract."},
    {"Embuscade : des bandits ennemis attaquent le convoi.","Ambush: enemy bandits attack the convoy."},
    {"Vendeur ambulant de la Guilde - Village des Pecheurs","Guild Street Vendor - Fishing Village"},
    {"- Negociation du prix et des conditions des contrats","- Negotiation of price and contract conditions"},
    {"Debloque la tenue et l'armure standard de la Guilde.","Unlocks the standard Guild outfit and armor."},
    {"[ G ]  GUILDE DES CONTRATS   |   OFFRES DISPONIBLES","[ G ] GUILD OF CONTRACTS |   OFFERS AVAILABLE"},
    {"Pantalon leger porte par le personnel de la Guilde.","Light pants worn by Guild staff."},
    {"Soldat de recouvrement de la Guilde des Mercenaires","Recovery Soldier of the Mercenary Guild"},
    {"\n\nPRIMES VERROUILLEES : niveau 1 de Guilde requis.","LOCKED BOUNTS: Guild level 1 required."},
    {"Maison detectee. Verification des places terminee.","House detected. Verification of places completed."},
    {"Prothese de bras gauche aux couleurs de la Guilde.","Prosthetic left arm in Guild colors."},
    {"THE MERCENARY   |   TABLEAU DES OFFRES DE CONTRATS","THE MERCENARY |   CONTRACT OFFER TABLE"},
    {"Expliquez-moi comment cette somme a ete calculee.","Explain to me how this amount was calculated."},
    {"Un client vient d'arriver avec un contrat urgent.","A client has just arrived with an urgent contract."},
    {"Reputation locale (%s) : %+.1f — %s. Total : %.1f","Local reputation (%s): %+.1f — %s. Total: %.1f"},
    {"THE MERCENARIE   |   POSTE DE COMMANDE — CONTRATS","THE MERCENARIE   |   COMMAND POST — CONTRACTS"},
    {"J'ai fait beaucoup de route pour venir jusqu'ici.","I traveled a long way to get here."},
    {"Prothese de bras droit aux couleurs de la Guilde.","Prosthetic right arm in Guild colors."},
    {"Recouvrement fiscal de la Guilde des Mercenaires","Mercenary Guild Tax Recovery"},
    {"Gilet leger porte par le personnel de la Guilde.","Light vest worn by Guild staff."},
    {"Je peux faire quelque chose pour toi, vagabond ?","Can I do anything for you, wanderer?"},
    {" << static_cast<int>(offer.distance/1000.0f) << ","<< static_cast<int>(offer.distance/1000.0f) <<"},
    {"Merci. Je prefere voyager avec vous qu'avec eux.","THANKS. I'd rather travel with you than with them."},
    {"Aucune zone connue.\nTerminez un premier contrat.","No known areas.\nComplete a first contract."},
    {"Bottes plaquees concues pour les longues routes.","Flat boots designed for long routes."},
    {"Guild Escort: contract dialogue added to barman","Guild Escort: contract dialogue added to bartender"},
    {"Contrat annule : le voyageur a ete mis en cage.","Contract canceled: the traveler was put in a cage."},
    {"Katana forge pour les combattants de la Guilde.","Katana forges for Guild fighters."},
    {" << static_cast<int>(offer.distance/500.0f) << ","<< static_cast<int>(offer.distance/500.0f) <<"},
    {"Collecteur fiscal de la Guilde des Mercenaires","Mercenary Guild Tax Collector"},
    {"Combien de temps faudra-t-il encore attendre ?","How much longer will we have to wait?"},
    {"Je trouverai une autre compagnie. Bonne route.","I will find another company. Have a good trip."},
    {"Votre dette est enregistree. Nous reviendrons.","Your debt is recorded. We will come back."},
    {"Le voyageur vous attend : revenez pres de lui.","The traveler is waiting for you: come back to him."},
    {"Cette Guilde semble tres demandee aujourd'hui.","This Guild seems in high demand today."},
    {"Vous etes la compagnie envoyee par le barman ?","Are you the company sent by the bartender?"},
    {" CONTRAT RARE : danger et recompense doubles.","RARE CONTRACT: double danger and reward."},
    {" Une nouvelle insistance annulera le contrat.","Further insistence will void the contract."},
    {"Guild Escort: could not hook dialogue actions","Guild Escort: could not hook dialogue actions"},
    {"THE MERCENARIE   POSTE DE COMMANDE — CONTRATS","THE MERCENARIE   COMMAND POST — CONTRACTS"},
    {"Contrat refuse : aucune somme n'a ete versee.","Contract refused: no amount was paid."},
    {"PRIMES / POURBOIRES\nConditionnels - non taxes","BONUSES / TIPS\nConditional - tax-free"},
    {"Un client VIP souhaite rencontrer la Guilde.","A VIP client wants to meet the Guild."},
    {"THE MERCENARY   |   NEGOCIATION D'EXPEDITION","THE MERCENARY |   EXPEDITION NEGOTIATION"},
    {"%s  |  %s  |  Distance depuis %s : %.1f km%s","%s |  %s |  Distance from %s: %.1f km%s"},
    {"RESUME GLOBAL\n\nRevenus bruts des contrats : ","OVERALL SUMMARY\n\nGross contract revenue:"},
    {"Clients physiques dans les Maisons de Guilde","Physical clients in Guild Houses"},
    {"<<static_cast<int>(offer.distance/1000.0f)<<","<<static_cast<int>(offer.distance/1000.0f)<<"},
    {"Tres bien, combien est-ce que je vous dois ?","Very good, how much do I owe you?"},
    {"Excellent travail. Voici aussi un pourboire.","Excellent work. Here's a tip too."},
    {"Je transporte une lettre importante jusqu'a ","I am carrying an important letter to"},
    {"L'escorte commence. Restez pres du voyageur.","The escort begins. Stay close to the traveler."},
    {"ALERTE CONTRAT : le client est inconscient.","CONTRACT ALERT: the customer is unconscious."},
    {"Plastron reserve aux sergents de la Guilde.","Breastplate reserved for Guild sergeants."},
    {"Guild Escort: could not hook dialogue event","Guild Escort: could not hook dialogue event"},
    {"Casque de protection standard de la Guilde.","Standard Guild protective helmet."},
    {"THE MERCENARY   |   NEGOCIATION DE CARAVANE","THE MERCENARY |   CARAVAN NEGOTIATION"},
    {"Bottes reservees aux sergents de la Guilde.","Boots reserved for Guild sergeants."},
    {"Matiere du pantalon de service de la Guilde","Material of Guild Service Trousers"},
    {"Plastron robuste aux couleurs de la Guilde.","Sturdy breastplate in Guild colors."},
    {"Debloque les armes forgees pour la Guilde.","Unlocks weapons forged for the Guild."},
    {"REUSSI - progression de Guilde privilegiee","PASSED - Privileged Guild progression"},
    {"THE MERCENARIE   |   CONDITIONS DU CONTRAT","THE MERCENARY |   CONDITIONS OF CONTRACT"},
    {"Un client propose un contrat exceptionnel.","A client offers an exceptional contract."},
    {"Ouvrir directement le tableau des contrats","Open the contracts table directly"},
    {"Batiment defini comme Maison de Guilde : ","Building defined as Guild House:"},
    {"Contrat : Expedition scientifique\nChef : ","Contract: Scientific Expedition\nLead scientist: "},
    {" Il vous attendra si vous etes trop loin.","He will wait for you if you are too far away."},
    {"Oui, montre-moi les armures de la Guilde.","Yes, show me the Guild armor."},
    {"THE MERCENARY   |   NEGOCIATION D'ESCORTE","THE MERCENARY |   ESCORT NEGOTIATION"},
    {"Matiere du pantalon samourai de la Guilde","Material of the Guild samurai pants"},
    {"Casque reserve aux sergents de la Guilde.","Helmet reserved for Guild sergeants."},
    {"VOTRE GUILDE VIENT D'ATTEINDRE LE NIVEAU ","YOUR GUILD JUST REACHED THE LEVEL"},
    {"INCIDENT : controle d'une faction locale.","INCIDENT: control of a local faction."},
    {"Travelling Guild Vendor - Fishing Village","Traveling Guild Vendor - Fishing Village"},
    {"Dans ce cas, notre affaire s'arrete ici.","In this case, our matter ends here."},
    {"Sous-vetement aux couleurs de la Guilde.","Underwear in Guild colors."},
    {"Verrouille jusqu'au niveau 3 de Guilde.\n","Locks up to Guild Level 3."},
    {"Matiere des bras robotiques de la Guilde","Material of the Guild's robotic arms"},
    {"client parti apres une attente excessive","customer left after excessive waiting"},
    {"Pantalon renforce de la tenue de Guilde.","Reinforced pants from the Guild outfit."},
    {"Je veux recommencer une nouvelle vie a ","I want to start a new life"},
    {"Je n'ai pas cette somme pour le moment.","I don't have that amount at the moment."},
    {"Un contrat d'escorte est deja en cours.","An escort contract is already in progress."},
    {"Contrat : Escorte de caravane\nMaitre : ","Contract: Caravan Escort\nMaster:"},
    {"Matiere du pantalon plaque de la Guilde","Material of the Guild plate pants"},
    {"Ce contrat est termine. Nous repartons.","This contract has ended. We are leaving again."},
    {"Merci. Vous avez tenu votre engagement.","THANKS. You kept your commitment."},
    {"Verrouille jusqu'au niveau 3 de Guilde.","Locked until Guild level 3."},
    {"\n\nINDISPONIBLE : contrat deja accepte.","UNAVAILABLE: contract already accepted."},
    {"Contrat annule : le voyageur est mort.","Contract canceled: the traveler is dead."},
    {"Soldat de recouvrement des Cites Unies","United Cities recovery soldier"},
    {"Contrat echoue : le voyageur est mort.","Contract fails: the traveler is dead."},
    {"Le donneur du contrat est introuvable.","The contract giver cannot be found."},
    {"Guild Escort: mission data unavailable","Guild Escort: mission data unavailable"},
    {"RAPPORT DE MISSION — REUSSITE\n\nTYPE : ","MISSION REPORT — SUCCESS\n\nTYPE:"},
    {"Aucun contrat termine pour le moment.","No contracts closed at the moment."},
    {"BILAN DU CONTRAT | NEGOCIATION FINALE","CONTRACT REVIEW | FINAL NEGOTIATION"},
    {"Un prix honnete. Je m'en souviendrai.","A fair price. I will remember it."},
    {"THE MERCENARY   |   ACCORD DE MISSION","THE MERCENARY |   MISSION AGREEMENT"},
    {"Nous approchons de notre destination.","We are approaching our destination."},
    {"Tres bien. Discutons des conditions.","Alright. Let's discuss the conditions."},
    {"<<e.destination<<mercenarieLocalize(","<<e.destination<<mercenarieLocalize("},
    {"L'acompte a ete rembourse au client.","The deposit was refunded to the customer."},
    {"Bras Robotique de la Guilde (gauche)","Guild Robotic Arm (left)"},
    {"RELATIONS ET INFLUENCE DE LA GUILDE","GUILD RELATIONS AND INFLUENCE"},
    {"Marché conclu. Vous savez negocier.","Deal concluded. You know how to negotiate."},
    {")<<FiscalLedger::rate(o,relation)<<",")<<FiscalLedger::rate(o,relation)<<"},
    {"  |  Danger estime selon le contrat","|  Danger estimated according to the contract"},
    {"Recouvrement fiscal des Cites Unies","Tax recovery of the United Cites"},
    {"Matiere du masque noir de la Guilde","Material of the black mask of the Guild"},
    {"Bras Robotique de la Guilde (droit)","Guild Robotic Arm (right)"},
    {"Contrat echoue par le menu de test.","Contract fails via test menu."},
    {"<<FiscalLedger::rate(o,relation)<<","<<FiscalLedger::rate(o,relation)<<"},
    {"Le voyageur n'a pas pu apparaitre.","The traveler could not appear."},
    {"Aucune mission active a terminer.","No active missions to complete."},
    {"Marchand de caravane de la Guilde","Guild Caravan Trader"},
    {"Collecteur fiscal des Cites Unies","United Cites tax collector"},
    {"Un atelier attend ma livraison a ","A workshop is awaiting my delivery in "},
    {"Accueil du marchand de la Guilde","Guild Merchant's Home"},
    {"DEFINIR COMME BATIMENT DE GUILDE","SET AS GUILD BUILDING"},
    {"Trois Maisons de Guilde au total","Three Guild Houses in total"},
    {"* NIVEAU DE GUILDE SUPERIEUR ! *","* HIGHER GUILD LEVEL! *"},
    {"Toutes les primes | XP inchangee","All bonuses | Unchanged XP"},
    {"REGISTRE DES REPUTATIONS LOCALES","REGISTER OF LOCAL REPUTATIONS"},
    {"\nPROGRESSION APRES VALIDATION : ","PROGRESS AFTER VALIDATION:"},
    {"Matiere du plastron de la Guilde","Guild Breastplate Material"},
    {"Pantalon de service de la Guilde","Guild Service Trousers"},
    {"Moitie des primes | XP inchangee","Half of the bonuses | Unchanged XP"},
    {"Maison de Guilde enregistree : ","Registered Guild House:"},
    {"Matiere des bottes de la Guilde","Guild Boot Material"},
    {"Plastron de la Guilde (Sergent)","Guild Breastplate (Sergeant)"},
    {"Maitre de caravane de la Guilde","Guild Caravan Master"},
    {"Je voudrais acheter une armure.","I would like to buy armor."},
    {"Mobilier de la Maison de Guilde","Guild House Furniture"},
    {"TABLEAU DES OFFRES — 6 CONTRATS","TABLE OF OFFERS — 6 CONTRACTS"},
    {"Une embuscade ! Preparez-vous !","An ambush! Get ready!"},
    {"Transporter une cargaison vers ","Transport cargo to"},
    {"Reponse quitter commerce Guilde","Response quit trade Guild"},
    {"Grande expedition scientifique","Great scientific expedition"},
    {"\nACCUEIL PHYSIQUE DES CLIENTS\n","PHYSICAL WELCOME OF CUSTOMERS"},
    {"Matiere du casque de la Guilde","Guild Helmet Material"},
    {"notre compagnie de mercenaires","our mercenary company"},
    {"Plastron de la Guilde (Leader)","Guild Breastplate (Leader)"},
    {"Matiere du plastron de Sergent","Material of Sergeant's breastplate"},
    {"D'accord. Je vous attends ici.","All right. I'm waiting for you here."},
    {"Total des revenus\ndes contrats","Total contract\nincome"},
    {"Stock du vendeur de la Guilde","Guild Vendor Stock"},
    {"Matiere du plastron de Leader","Material of Leader's breastplate"},
    {"Un contrat est deja en cours.","A contract is already in progress."},
    {"Matiere des bottes de Sergent","Material of Sergeant's boots"},
    {"Gilet de service de la Guilde","Guild Service Vest"},
    {"SIMULER RECHERCHE VERROUILLEE","SIMULATE LOCKED SEARCH"},
    {"Casque de la Guilde (Sergent)","Guild Helmet (Sergeant)"},
    {"Armure de la Guilde (Sergent)","Guild Armor (Sergeant)"},
    {"Bottes de la Guilde (Sergent)","Guild Boots (Sergeant)"},
    {"Le voyageur reprend la route.","The traveler hits the road again."},
    {"Matiere du casque de Sergent","Material of Sergeant's helmet"},
    {"Matiere des bottes de Leader","Material of Leader Boots"},
    {"Accueil du collecteur fiscal","Home of the tax collector"},
    {"Casque de la Guilde (Leader)","Guild Helmet (Leader)"},
    {"Bottes de la Guilde (Leader)","Guild Boots (Leader)"},
    {"Armure de la Guilde (Leader)","Guild Armor (Leader)"},
    {"EPIQUE - CLIENT EXCEPTIONNEL","EPIC - EXCEPTIONAL CUSTOMER"},
    {"BUREAUX ET MAISONS DE GUILDE","GUILD OFFICES AND HOUSES"},
    {"Voyageur pour Griffure Noire","Traveler for Black Claw"},
    {"Voyageur pour Bout-du-Monde","Traveler to Bout-du-Monde"},
    {"Acheter pantalons et bottes","Buy pants and boots"},
    {"Acheter armures et t-shirts","Buy armor and t-shirts"},
    {"Equipe scientifique de test","Scientific test team"},
    {"Matiere du casque de Leader","Leader helmet material"},
    {"contrat echoue ou abandonne","contract fails or abandons"},
    {"Mon pere malade m'attend a ","My sick father is waiting for me in "},
    {"DEFINIR BATIMENT DE GUILDE","DEFINE GUILD BUILDING"},
    {"SIMULER RECHERCHE TERMINEE","SIMULATE SEARCH COMPLETED"},
    {"Siege du collecteur fiscal","Headquarters of the tax collector"},
    {"Modele d'arme de la Guilde","Guild Weapon Model"},
    {" XP\nXP TOTAL DE GUILDE : +","XP\nTOTAL GUILD XP: +"},
    {"Accueil barman et contrats","Bartender reception and contracts"},
    {"[X] Aucune blessure grave\n","[X] No serious injuries"},
    {"%d Cats avant negociation.","%d Cats before negotiation."},
    {".  [MAISON DE GUILDE]\n    ",".  [GUILD HOUSE]"},
    {"Acheter casques et masques","Buy helmets and masks"},
    {"- Primes de fin de mission","- End of mission bonuses"},
    {"DECLENCHER COLLECTE GUILDE","TRIGGER GUILD COLLECTION"},
    {" XP\nPROCHAIN DEBLOCAGE : ","XP\nNEXT UNLOCK:"},
    {"/5)\nDISTANCE PARCOURUE : ","/5)\nDISTANCE TRAVELED:"},
    {" XP\nPROCHAIN DEBLOCAGE :\n","XP\nNEXT UNLOCK:"},
    {"Premiere rencontre client","First customer meeting"},
    {"Presentation de la Guilde","Presentation of the Guild"},
    {"Atelier des Terres mortes","Deadlands Workshop"},
    {"-20%  FAVORABLE AU CLIENT","-20% FAVORABLE TO THE CUSTOMER"},
    {"Sans prime | Reputation +","Without premium | Reputation +"},
    {"BATIMENT DE GUILDE DEFINI","GUILD BUILDING DEFINED"},
    {"Maison de Guilde sans nom","Unnamed Guild House"},
    {"NOUVELLE MAISON DE GUILDE","NEW GUILD HOUSE"},
    {"Niveau de Guilde 3 requis","Guild level 3 required"},
    {"REUSSI - primes demandees","SUCCESS - bonuses requested"},
    {"Etudier les vestiges de ","Study the remains of"},
    {"Accepter la contre-offre","Accept the counteroffer"},
    {"Negociation des contrats","Negotiation of contracts"},
    {"Contrat : Escorte\nPNJ : ","Contract: Escort\nNPC:"},
    {"Primes de fin de mission","End of mission bonuses"},
    {"Bonus de remuneration : ","Payment bonus: "},
    {"Je reviendrai vous voir.","I will come back to see you."},
    {"Cargaison exceptionnelle","Exceptional cargo"},
    {"service d'escorte reussi","successful escort service"},
    {"PROGRESSION DE LA GUILDE","PROGRESSION OF THE GUILD"},
    {"Conditions insuffisantes","Requirements not met"},
    {"Frais de ravitaillement","Refueling costs"},
    {"SELECTIONNER CE CONTRAT","SELECT THIS CONTRACT"},
    {"[X] Embuscade survecue\n","[X] Survived ambush"},
    {"Reponse commerce Guilde","Guild Trade Reply"},
    {"proteger les recherches","protect research"},
    {"EXPEDITION SCIENTIFIQUE","SCIENTIFIC EXPEDITION"},
    {":relation==FREL_ALLIED?",":relation==FREL_ALLIED?"},
    {"prochaine rotation dans","next rotation in"},
    {"  |  TEMPS MERCENARIE +","|  MERCENARY TIME +"},
    {"  |  REPUTATION LOCALE ","|  LOCAL REPUTATION"},
    {"POURBOIRE DU CLIENT : +","CUSTOMER TIP: +"},
    {"RENOUVELER LES 6 OFFRES","RENEW THE 6 OFFERS"},
    {"\n\n[CONTRAT PRESTIGIEUX]","[PRESTIGIOUS CONTRACT]"},
    {"ACCEPTER LES CONDITIONS","ACCEPT THE TERMS"},
    {"Caravane exceptionnelle","Exceptional caravan"},
    {"Expedition scientifique","Scientific expedition"},
    {"HISTORIQUE DES CONTRATS","CONTRACT HISTORY"},
    {"Caravane technologique","Technological caravan"},
    {"ZONES ET REPUTATIONS\n\n","AREAS AND REPUTATIONS"},
    {"RENOUVELLEMENT DANS : ","RENEWAL IN:"},
    {"Zone: Zone frontalière","Area: Border area"},
    {"%\n\nREPUTATION GLOBALE\n","%\n\nGLOBAL REPUTATION"},
    {"Laboratoire des marais","Swamp Laboratory"},
    {"Avance : 0% (max. 50%)","Feed: 0% (max. 50%)"},
    {"Le Masque de la Guilde","The Guild Mask"},
    {"RELATIONS DE LA GUILDE","GUILD RELATIONS"},
    {"Clic gauche : deplacer","Left click: move"},
    {"Guilde des Mercenaires","Mercenary Guild"},
    {"Compagnie experimentee","Experienced company"},
    {"Je cherche un contrat.","I'm looking for a contract."},
    {"GUILDE DES MERCENAIRES","MERCENARY GUILD"},
    {"SUPPRIMER CLIENTS TEST","REMOVE TEST CLIENTS"},
    {"Marchand de la Guilde","Guild Merchant"},
    {"Minerais et materiaux","Ores and materials"},
    {"Voyageur pour Mongrel","Traveler for Mongrel"},
    {"Pantalon de la Guilde","Guild Trousers"},
    {"Maitre de caravane : ","Caravan master:"},
    {"CONDITIONS DU CONTRAT","CONDITIONS OF CONTRACT"},
    {"FINANCES ET FISCALITE","FINANCES AND TAXATION"},
    {"FAIRE VENIR 3 CLIENTS","SUMMON 3 CLIENTS"},
    {"REPUTATION PREVUE : +","EXPECTED REPUTATION: +"},
    {"\nREPUTATION LOCALE : ","LOCAL REPUTATION:"},
    {"Veterans de la Guilde","Guild Veterans"},
    {"Plastron de la Guilde","Guild Breastplate"},
    {"Phase de recherche a ","Research phase a"},
    {"VOS MAISONS DE GUILDE","YOUR GUILD HOUSES"},
    {"Zone: Îles brumeuses","Area: Misty Isles"},
    {"EN ATTENTE DU JOUEUR","WAITING FOR PLAYER"},
    {"Cargaison importante","Large cargo"},
    {"First client meeting","First customer meeting"},
    {"rejoindre les ruines","join the ruins"},
    {"Chef scientifique : ","Chief scientist:"},
    {" Cats et reputation\n","Cats and reputation"},
    {" avant de revenir a ","before returning to"},
    {"Accord pour discuter","Agreement to discuss"},
    {"Caravane alimentaire","Food caravan"},
    {" << offer.danger << ","<< offer.danger <<"},
    {"Maison de Guilde de ","Guild House of"},
    {"JOURNAL DES CONTRATS","CONTRACTS JOURNAL"},
    {"FAIRE VENIR 1 CLIENT","SUMMON 1 CLIENT"},
    {"REFUSER ET COMBATTRE","REFUSE AND FIGHT"},
    {"Jusqu'a 50% d'avance","Up to 50% in advance"},
    {"T-shirt de la Guilde","Guild T-shirt"},
    {"Katana de la Guilde","Guild Katana"},
    {"Village de pêcheurs","Fishing village"},
    {"Armure de la Guilde","Guild Armor"},
    {"Guilde prestigieuse","Prestigious guild"},
    {"Un nouveau client (","A new customer ("},
    {"DOSSIER SELECTIONNE","SELECTED FILE"},
    {"Bottes de la Guilde","Guild Boots"},
    {"Retour aux contrats","Back to contracts"},
    {"EPIQUE - CLIENT VIP","EPIC - VIP CUSTOMER"},
    {"ACCEPTER LE CONTRAT","ACCEPT THE CONTRACT"},
    {"Mauvaise reputation","Bad reputation"},
    {"Escorte de caravane","Caravan Escort"},
    {"Caravane importante","Large caravan"},
    {"Casque de la Guilde","Guild Helmet"},
    {"Cargaison precieuse","Valuable cargo"},
    {"Equipe scientifique","Scientific team"},
    {"VALIDER ET PROPOSER","VALIDATE AND PROPOSE"},
    {"Aucun contrat actif","No active contract"},
    {"0%  OFFRE DU CLIENT","0% CUSTOMER OFFER"},
    {"RECHERCHE TERMINEE","SEARCH COMPLETED"},
    {"TESTER LES CHAISES","TEST THE CHAIRS"},
    {"\nXP DE MISSION : +","MISSION XP: +"},
    {"OFFRES DISPONIBLES","AVAILABLE OFFERS"},
    {"Marchand itinerant","Traveling merchant"},
    {"Armes de la Guilde","Guild Weapons"},
    {"CONFIRMER LE REFUS","CONFIRM REFUSAL"},
    {"GENERER EXPEDITION","GENERATE EXPEDITION"},
    {"CHOISIR CE CONTRAT","CHOOSE THIS CONTRACT"},
    {"\nPRIME MAXIMALE : ","MAXIMUM PREMIUM:"},
    {"CONTRAT EN COURS\n\n","CURRENT CONTRACT"},
    {"Zone: Grand Désert","Area: Great Desert"},
    {"43355-Dialogue.mod","43355-Dialogue.mod"},
    {"Refuser le contrat","Refuse the contract"},
    {"ENREGISTRER LE NOM","SAVE NAME"},
    {"Caravane precieuse","Precious caravan"},
    {"REPUTATION / TEMPS","REPUTATION / TIME"},
    {"Cargaison commune","Joint cargo"},
    {"Chef scientifique","Chief scientist"},
    {"Cargaison basique","Basic cargo"},
    {"RARE - CLIENT VIP","RARE - VIP CUSTOMER"},
    {"Caravane medicale","Medical caravan"},
    {"CLIENTS ET MAISON","CLIENTS AND GUILD HOUSE"},
    {"\nBONUS DANGER : +","BONUS DANGER: +"},
    {"REPUTATION NEUTRE","NEUTRAL REPUTATION"},
    {"Reprendre escorte","Resume escort"},
    {"<<e.destination<<","<<e.destination<<"},
    {"DISTANCE / RISQUE","DISTANCE / RISK"},
    {"PRIME POTENTIELLE","POTENTIAL BONUS"},
    {"CONTRAT D'ESCORTE","ESCORT CONTRACT"},
    {"Guilde legendaire","Legendary Guild"},
    {"NIVEAU DE GUILDE","GUILD LEVEL"},
    {"GUILDE — NIVEAU ","GUILD — LEVEL"},
    {"NETTOYER CONTRAT","CLEAN CONTRACT"},
    {"Caravane de luxe","Luxury caravan"},
    {"MISSION-%.3f-%lu","MISSION-%.3f-%lu"},
    {"Village Pecheurs","Fishing Village"},
    {"Caravane miniere","Mining caravan"},
    {"Chaise d'Attente","Waiting Chair"},
    {"Caravane basique","Basic caravan"},
    {"PAIEMENT DEMANDE","PAYMENT REQUEST"},
    {"Village Pêcheurs","Fishing Village"},
    {"Caravane de test","Test caravan"},
    {"Grande compagnie","Great company"},
    {"Caravane commune","Common caravan"},
    {"RAID 3 EN COMBAT","RAID 3 IN COMBAT"},
    {"GENERER CARAVANE","GENERATE CARAVAN"},
    {"Maison de Guilde","Guild House"},
    {"RAID 2 EN COMBAT","RAID 2 IN COMBAT"},
    {"Guilde naissante","Emerging Guild"},
    {"RAID 1 EN COMBAT","RAID 1 IN COMBAT"},
    {"PAYER GUILDE : ","PAY GUILD:"},
    {"Prime de danger","danger premium"},
    {"Guilde reconnue","Recognized guild"},
    {"combat defensif","defensive combat"},
    {" avec pourboire","with tip"},
    {"Guilde inconnue","Unknown Guild"},
    {"\nProgression : ","Progress:"},
    {"\nDestination : ","Destination :"},
    {"GENERER ESCORTE","GENERATE ESCORT"},
    {"Remuneration : ","Payment: "},
    {"Flotsam Village","Flotsam Village"},
    {"CONTRAT ACCEPTE","CONTRACT ACCEPTED"},
    {"Fishing Village","Fishing Village"},
    {") est arrive a ",") arrived at"},
    {"Escorte Mission","Escort Mission"},
    {"Contrat de test","Test contract"},
    {"Village Flotsam","Flotsam Village"},
    {"Ville inconnue","Unknown city"},
    {"CONTRAT PROCHE","NEAR CONTRACT"},
    {"TOUS LES LIEUX","ALL LOCATIONS"},
    {"Impact positif","Positive impact"},
    {"RENSEIGNEMENTS","INTELLIGENCE"},
    {"Molette : zoom","Mouse wheel: zoom"},
    {"Guilde reputee","Renowned guild"},
    {"CARTE DU MONDE","WORLD MAP"},
    {"+10 REPUTATION","+10 REPUTATION"},
    {"-10 REPUTATION","-10 REPUTATION"},
    {"Mission Escort","Escort mission"},
    {"SUCCES CONTRAT","CONTRACT SUCCESS"},
    {"Chaise Client","Client Chair"},
    {"\n    Ville : ","City :"},
    {"Bout-du-Monde","World's End"},
    {"Guilde locale","Local guild"},
    {" km retour = ","km return ="},
    {"Avance : %d%%","Advance: %d%%"},
    {". Paiement : ",". Payment :"},
    {"ECHEC CONTRAT","CONTRACT FAILURE"},
    {"  |  ACCUEIL ","|  WELCOME"},
    {"  |  CONTRAT ","|  CONTRACT"},
    {"trajet retour","return journey"},
    {"Pause escorte","Escort break"},
    {"[X] Aucun KO\n","[X] No KO"},
    {"\n\nTOTAL DU : ","TOTAL OF:"},
    {"CONTRAT MOYEN","MEDIUM CONTRACT"},
    {"Vivres et eau","Food and water"},
    {"Client Chair","Client Chair"},
    {"\nDISTANCE : ","DISTANCE :"},
    {"CONTRAT LONG","LONG CONTRACT"},
    {" km\nDUREE : ","km\nDURATION:"},
    {"CARGAISON : ","CARGO:"},
    {"Scientifique","Scientist"},
    {"RECOMPENSES","REWARDS"},
    {"  >  RETOUR","> BACK"},
    {"] | GUILDE ","] | GUILD"},
    {"AUCUN DELAI","NO DELAY"},
    {"\n\nDEPART : ","DEPARTURE :"},
    {"\n\nCLIENT : ","CUSTOMER :"},
    {"Voyageur : ","Traveler:"},
    {"avant-poste","outpost"},
    {"\nTRAJET : ","ROUTE :"},
    {"\nMAISON : ","HOME :"},
    {"\nDepart : ","Departure :"},
    {"\nDANGER : ","HAZARD :"},
    {" | Guilde ","| Guild"},
    {"REPUTATION","REPUTATION"},
    {"ITINERAIRE","ROUTE"},
    {"Mercenaire","Mercenary"},
    {"EXPEDITION","EXPEDITION"},
    {" aller + ","go +"},
    {"personnes","people"},
    {"NIVEAU 10","LEVEL 10"},
    {"-1 NIVEAU","-1 LEVEL"},
    {"+1 NIVEAU","+1 LEVEL"},
    {"NIVEAU 5","LEVEL 5"},
    {"NIVEAU 3","LEVEL 3"},
    {"NIVEAU 1","LEVEL 1"},
    {"personne","person"},
    {"Caravane","Caravan"},
    {"PAIEMENT","PAYMENT"},
    {"Voyageur","Traveler"},
    {"Marchand","Merchant"},
    {"ESCORTE","ESCORT"},
    {"village","village"},
    {"NIVEAU ","LEVEL"},
    {"ARRIVEE","ARRIVAL"},
    {"RETOUR","RETURN"},
    {"DEPART","DEPARTURE"},
    {"GROUPE","GROUP"},
    {"offres","offers"},
    {"barman","bartender"},
    {"Soldat","Soldier"},
    {"jours","days"},
    {"AUCUN","NONE"},
    {"Noble","Noble"},
    {"VILLE","CITY"},
    {"ECHEC","FAILURE"},
    {"Pas un de plus. Nous reviendrons a cette date.","Not one day more. We will return on that date."},
    {"Tres bien, reprenons la route.","Very well, let us continue on our way."},
    {"Tres bien. Discutons des conditions.","Very well. Let us discuss the terms."},
    {"TARIF AU KILOMETRE","RATE PER KILOMETER"},
    {"VOIR LE DETAIL","VIEW DETAILS"},
    {"Insister (risque d'annulation)","Insist (risk cancellation)"},
    {"Cette porte pourrait encore ceder. Je vais tenter de crocheter sa serrure.","This door may still give way. I will try to pick its lock."},
    {"Nous progressons bien. Merci de rester pres de moi.","We are making good progress. Please stay close to me."},
    {"Le passage principal semble dangereux. Faisons un detour prudent.","The main passage looks dangerous. Let us take a cautious detour."},
    {"INCIDENT : detour dangereux signale sur la route.","INCIDENT: dangerous detour reported on the road."},
    {"INCIDENT : mauvaise visibilite, le groupe ralentit.","INCIDENT: poor visibility, the group is slowing down."},
    {"MERCENARIE — MENU DE TEST","MERCENARY — TEST MENU"},
    {"OUTILS DE DEVELOPPEMENT ET DE TEST","DEVELOPMENT AND TEST TOOLS"},
    {"Leur utilisation peut modifier la progression de votre partie.","Using them may alter your game progress."},
    {"VOIR LE DETAIL","VIEW DETAILS"},
    {"+25%  DEMANDE RISQUEE","+25% RISKY DEMAND"},
    {"Cette tempete reduit la visibilite. Resserrez la formation.","This storm reduces visibility. Tighten the formation."},
    {"Nous progressons bien. Merci de rester pres de moi.","We are making good progress. Please stay close to me."},
};
