#pragma once
#include <algorithm>
#include <cctype>
#include <string>
#include <vector>

namespace MissionBookContracts {

enum Category { All=0, Legal=1, Illegal=2, Merchant=3, Security=4 };
enum SoldierSort { SortName=0, SortAttack=1, SortDefence=2, SortEndurance=3 };
enum { PageSize=7 };

struct Offer {
    std::string id;
    Category category;
    bool available;
    Offer(const std::string& stableId=std::string(),Category c=Legal,bool enabled=true)
        :id(stableId),category(c),available(enabled){}
};

inline Category categoryFor(int missionType,bool securitySource)
{
    if(securitySource)return Security;
    // Existing mission metadata is authoritative: caravan and mail are the
    // commercial families; escort/science remain legal. No illegal source is
    // currently generated by the runtime.
    return missionType==1||missionType==4?Merchant:Legal;
}

inline bool visible(Category filter,Category offer)
{
    return filter==All||filter==offer;
}

inline std::vector<size_t> filtered(const std::vector<Offer>& offers,Category filter)
{
    std::vector<size_t> result;
    for(size_t i=0;i<offers.size();++i)if(offers[i].available&&visible(filter,offers[i].category))result.push_back(i);
    return result;
}

struct Soldier {
    std::string stableId,name;
    int attack,defence,endurance;
    Soldier(const std::string& id=std::string(),const std::string& display=std::string(),int a=0,int d=0,int e=0)
        :stableId(id),name(display),attack(a),defence(d),endurance(e){}
};

inline std::string folded(std::string value)
{
    for(size_t i=0;i<value.size();++i)value[i]=(char)std::tolower((unsigned char)value[i]);
    return value;
}

inline void sortSoldiers(std::vector<size_t>& order,const std::vector<Soldier>& soldiers,SoldierSort mode)
{
    std::stable_sort(order.begin(),order.end(),[&](size_t a,size_t b)->bool{
        const Soldier& x=soldiers[a];const Soldier& y=soldiers[b];
        if(mode==SortAttack&&x.attack!=y.attack)return x.attack>y.attack;
        if(mode==SortDefence&&x.defence!=y.defence)return x.defence>y.defence;
        if(mode==SortEndurance&&x.endurance!=y.endurance)return x.endurance>y.endurance;
        const std::string xn=folded(x.name),yn=folded(y.name);
        if(xn!=yn)return xn<yn;
        return x.stableId<y.stableId;
    });
}

inline int pageCount(size_t rows,size_t pageSize){return pageSize?std::max(1,(int)((rows+pageSize-1)/pageSize)):1;}
inline int clampPage(int page,size_t rows){return std::max(0,std::min(page,pageCount(rows,PageSize)-1));}
inline std::vector<size_t> page(const std::vector<size_t>& rows,int requested){
    const size_t begin=clampPage(requested,rows.size())*PageSize;
    return std::vector<size_t>(rows.begin()+begin,rows.begin()+std::min(rows.size(),begin+PageSize));
}

}
