#pragma once
namespace NativeDismissObserver {
static bool active=false,detected=false,complete=false; static float elapsed=0,nextSample=0; static int sampleIndex=0; static hand target; static std::string targetName; static std::ofstream logFile;
static std::string oldFaction,oldPlatoon; static bool oldInPlayers=false,oldSelected=false,haveOld=false;
inline void write(const std::string&s){if(logFile.is_open())logFile<<s<<"\n"<<std::flush;DebugLog(std::string("[NATIVE DISMISS OBSERVER] ")+s);}
inline std::vector<Character*> selected(){std::vector<Character*>o;if(!ou||!ou->player)return o;for(ogre_unordered_set<hand>::type::const_iterator i=ou->player->selectedCharacters.begin();i!=ou->player->selectedCharacters.end();++i){Character*c=i->getCharacter();if(c&&c->getFaction()==ou->player->participant&&!c->isDead())o.push_back(c);}return o;}
inline std::string yn(bool v){return v?"YES":"NO";}
inline void snap(const char*l){Character*c=target.getCharacter();std::ostringstream s;s<<l<<" | handle="<<target.toString()<<" | valid="<<yn(c!=0);bool in=false,sel=false;std::string faction="<invalid>",platoon="<invalid>";if(c){int ix=-1;for(size_t i=0;ou&&ou->player&&i<ou->player->playerCharacters.size();++i)if(ou->player->playerCharacters[i]==c){in=true;ix=(int)i;break;}if(ou&&ou->player)for(ogre_unordered_set<hand>::type::const_iterator i=ou->player->selectedCharacters.begin();i!=ou->player->selectedCharacters.end();++i)if(i->getCharacter()==c){sel=true;break;}faction=c->getFaction()?c->getFaction()->name:"<none>";platoon=c->getPlatoon()&&c->getPlatoon()->me?c->getPlatoon()->me->getName():"<none>";s<<" | name="<<c->getName()<<" | faction="<<faction<<" | platoon="<<platoon<<" | active/loaded="<<yn(c->getPlatoon()!=0)<<" | playerCharacters="<<yn(in)<<" index="<<ix<<" | selected="<<yn(sel)<<" | pos="<<c->getPosition().x<<","<<c->getPosition().y<<","<<c->getPosition().z<<" | dead="<<yn(c->isDead())<<" | portrait=UNAVAILABLE_SAFE_API";}else s<<" | playerCharacters=NO | selected=NO | world=UNKNOWN | portrait=UNAVAILABLE_SAFE_API";write(s.str());if(haveOld){std::ostringstream d;d<<"CHANGES: playerCharacters "<<yn(oldInPlayers)<<" -> "<<yn(in)<<" | selected "<<yn(oldSelected)<<" -> "<<yn(sel)<<" | faction "<<oldFaction<<" -> "<<faction<<" | platoon "<<oldPlatoon<<" -> "<<platoon;write(d.str());}oldInPlayers=in;oldSelected=sel;oldFaction=faction;oldPlatoon=platoon;haveOld=true;}
inline void start(){if(active)return;std::vector<Character*>s=selected();int n=0;if(ou&&ou->player)for(size_t i=0;i<ou->player->playerCharacters.size();++i)if(ou->player->playerCharacters[i]&&!ou->player->playerCharacters[i]->isDead())++n;if(s.size()!=1||n<2){if(ou)ou->showPlayerAMessage("NATIVE DISMISS OBSERVER: select exactly one character and keep another playable character",true);return;}target=s[0]->getHandle();targetName=s[0]->getName();active=true;detected=complete=false;elapsed=nextSample=0;sampleIndex=0;logFile.open("mods/Guild Escort Contracts/NativeDismissObserver.log",std::ios::out|std::ios::trunc);write("[01] OBSERVER STARTED");write("[02] TARGET = "+targetName+" handle="+target.toString());write("[03] PRE-DISMISS SNAPSHOT");snap("PRE-DISMISS");if(ou)ou->showPlayerAMessage("OBSERVATION ACTIVE: use Squads -> select target -> DISMISS",true);}
inline void update(float dt){if(!active||complete)return;if(detected)elapsed+=dt;Character*c=target.getCharacter();bool in=false;if(ou&&ou->player)for(size_t i=0;i<ou->player->playerCharacters.size();++i)if(ou->player->playerCharacters[i]==c)in=true;if(!detected&&!in){detected=true;elapsed=0;write("[10] PLAYER CHARACTER REMOVAL DETECTED");snap("T+0");nextSample=.1f;}if(detected&&elapsed>=nextSample){static const char*ls[]={"T+100ms","T+500ms","T+1s","T+2s","T+5s","T+10s"};if(sampleIndex<6){snap(ls[sampleIndex]);++sampleIndex;nextSample=sampleIndex==1?.5f:sampleIndex==2?1:sampleIndex==3?2:sampleIndex==4?5:10;}else{write("[18] OBSERVATION COMPLETE");complete=true;active=false;logFile.close();}}}
}
