    struct DelegatedMissionState {
        int version,kind,reward,difficulty,sent,returned,injured,amputations,dead,guildXp,reputationDelta,paymentState;
        bool resultRolled,success,completed,reportShown;
        float successChance,successRoll;
        double completedAt;
        std::string groupId,offerIdentity,issuerIdentity,boardKey,title,origin,destination,officeKey,clientName,outcomeCode;
        DelegatedMissionTiming::State timing;
        DelegatedMissionState():version(4),kind(0),reward(0),difficulty(0),sent(0),returned(0),injured(0),amputations(0),dead(0),guildXp(0),reputationDelta(0),paymentState(0),resultRolled(false),success(false),completed(false),reportShown(false),successChance(0),successRoll(0),completedAt(0){}
        template<class Archive> void archive(Archive& a){a.field(version);a.field(kind);a.field(reward);a.field(offerIdentity);a.field(issuerIdentity);a.field(boardKey);a.field(title);a.field(origin);a.field(destination);timing.archive(a);if(!a.reading||version>=2){a.field(resultRolled);a.field(success);}else if(a.reading){resultRolled=true;success=true;}if(!a.reading||version>=3)a.field(groupId);else if(a.reading)groupId="legacy";if(!a.reading||version>=4){a.field(difficulty);a.field(sent);a.field(returned);a.field(injured);a.field(amputations);a.field(dead);a.field(guildXp);a.field(reputationDelta);a.field(paymentState);a.field(completed);a.field(reportShown);a.field(successChance);a.field(successRoll);a.field(completedAt);a.field(officeKey);a.field(clientName);a.field(outcomeCode);}else if(a.reading){difficulty=0;sent=returned=injured=amputations=dead=0;guildXp=35;reputationDelta=success?1:-1;paymentState=completed=reportShown=0;successChance=successRoll=0;completedAt=0;version=4;}if(a.reading&&((version<1||version>4)||kind<0||kind>2||reward<0||paymentState<0||paymentState>3||(timing.active&&!resultRolled)))throw std::runtime_error("invalid delegated mission");}
        void clear(){*this=DelegatedMissionState();}
    } delegatedMission;
    std::vector<DelegatedMissionState> delegatedMissions;
    void updateDelegatedMission()
    {
        for(size_t i=0;i<delegatedMissions.size();++i){DelegatedMissionState& mission=delegatedMissions[i];if(mission.completed){ensureDelegatedPaymentClient(mission);continue;}if(!mission.timing.active||!DelegatedMissionTiming::completed(mission.timing,currentGameHours))continue;if(!MissionAbsencePrototype::returnGroup(mission.groupId))continue;mission.timing.active=false;mission.completed=true;guildPayroll.complete(mission.groupId);mission.completedAt=currentGameHours;mission.returned=mission.sent;mission.injured=mission.amputations=mission.dead=0;mission.paymentState=mission.success?1:0;const std::string resultId="delegated-result:"+mission.groupId+":"+mission.offerIdentity;rewardedContractIds.insert(resultId);if(mission.success){++successfulContracts;GuildProgression::award(guildPoints,guildPrestige,mission.guildXp);escortReputation=GuildProgression::clampRep(escortReputation+(float)mission.reputationDelta);archiveDelegated(mission,1);}else{++failedContracts;escortReputation=GuildProgression::clampRep(escortReputation+(float)mission.reputationDelta);archiveDelegated(mission,2);}if(contractHistory.size()>50)contractHistory.resize(50);saveReputations();ensureDelegatedPaymentClient(mission);mission.reportShown=true;if(clientOptions.showNotifications&&clientOptions.notifyDelegatedComplete)showDelegatedReport((int)i);DebugLog(std::string("Delegated mission completed group=")+mission.groupId+" payment="+(mission.success?"pending":"none"));}
        int completedCount=0;for(int i=(int)delegatedMissions.size()-1;i>=0;--i)if(delegatedMissions[i].completed&&++completedCount>50&&delegatedMissions[i].paymentState!=1&&delegatedMissions[i].paymentState!=2)delegatedMissions.erase(delegatedMissions.begin()+i);
    }
